/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.resources.doc.metadata;

import com.cloudpdf.api.core.ClientOptions;
import com.cloudpdf.api.core.RequestOptions;
import com.cloudpdf.api.resources.doc.metadata.requests.GetMetadataRequest;
import com.cloudpdf.api.types.DocMetadataGet200Response;

public class MetadataClient {
    protected final ClientOptions clientOptions;

    private final RawMetadataClient rawClient;

    public MetadataClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawMetadataClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawMetadataClient withRawResponse() {
        return this.rawClient;
    }

    public DocMetadataGet200Response get(String docId, String layerName) {
        return this.rawClient.get(docId, layerName).body();
    }

    public DocMetadataGet200Response get(String docId, String layerName, RequestOptions requestOptions) {
        return this.rawClient.get(docId, layerName, requestOptions).body();
    }

    public DocMetadataGet200Response get(String docId, String layerName, GetMetadataRequest request) {
        return this.rawClient.get(docId, layerName, request).body();
    }

    public DocMetadataGet200Response get(
            String docId, String layerName, GetMetadataRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(docId, layerName, request, requestOptions).body();
    }
}
