plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.diffplug.spotless' version '6.11.0'
}

repositories {
    mavenCentral()
    maven {
        url 'https://s01.oss.sonatype.org/content/repositories/releases/'
    }
}

dependencies {
    api 'com.squareup.okhttp3:okhttp:5.2.1'
    api 'com.fasterxml.jackson.core:jackson-databind:2.18.6'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.18.6'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.6'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.2'
}


sourceCompatibility = 1.8
targetCompatibility = 1.8

tasks.withType(Javadoc) {
    failOnError false
    options.addStringOption('Xdoclint:none', '-quiet')
}

spotless {
    java {
        palantirJavaFormat()
    }
}


java {
    withSourcesJar()
    withJavadocJar()
}


group = 'com.cloudpdf'

version = '3.0.0-alpha.3'

jar {
    dependsOn(":generatePomFileForMavenPublication")
    archiveBaseName = "sdk"
}

sourcesJar {
    archiveBaseName = "sdk"
}

javadocJar {
    archiveBaseName = "sdk"
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.cloudpdf'
            artifactId = 'sdk'
            version = '3.0.0-alpha.3'
            from components.java
            pom {
                name = 'CloudPDF'
                description = 'The official Java SDK for the CloudPDF API.'
                url = 'https://www.cloudpdf.com'
                licenses {
                    license {
                        name = 'Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution = 'repo'
                    }
                }
                developers {
                    developer {
                        id = 'cloudpdf'
                        name = 'CloudPDF'
                        email = 'hello@cloudpdf.com'
                        organization = 'CloudPDF'
                        organizationUrl = 'https://www.cloudpdf.com'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/embedpdf/cloudpdf-sdk-java.git'
                    developerConnection = 'scm:git:ssh://git@github.com/embedpdf/cloudpdf-sdk-java.git'
                    url = 'https://github.com/embedpdf/cloudpdf-sdk-java'
                }
            }
        }
    }
    repositories {
        maven {
            name = 'centralStaging'
            url = layout.buildDirectory.dir('central-staging')
        }
    }
}


tasks.withType(GenerateModuleMetadata) {
    enabled = false
}

signing {
    useInMemoryPgpKeys(
        System.getenv('MAVEN_GPG_PRIVATE_KEY'),
        System.getenv('MAVEN_GPG_PASSPHRASE')
    )
    sign publishing.publications.maven
}
