/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.resources.doc.signatures;

import com.cloudpdf.api.core.ClientOptions;
import com.cloudpdf.api.core.RequestOptions;
import com.cloudpdf.api.resources.doc.signatures.requests.AbortSignaturesRequest;
import com.cloudpdf.api.resources.doc.signatures.requests.AnalysisSignaturesRequest;
import com.cloudpdf.api.resources.doc.signatures.requests.DocSignaturesCompleteRequest;
import com.cloudpdf.api.resources.doc.signatures.requests.ListSignaturesRequest;
import com.cloudpdf.api.resources.doc.signatures.requests.PrepareSignaturesRequest;
import com.cloudpdf.api.types.DocSignaturesAbort200Response;
import com.cloudpdf.api.types.DocSignaturesAnalysis200Response;
import com.cloudpdf.api.types.DocSignaturesComplete200Response;
import com.cloudpdf.api.types.DocSignaturesList200Response;
import com.cloudpdf.api.types.DocSignaturesPrepare200Response;
import java.io.File;
import java.io.InputStream;
import java.util.concurrent.CompletableFuture;
import okhttp3.MediaType;

public class AsyncSignaturesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSignaturesClient rawClient;

    public AsyncSignaturesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSignaturesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSignaturesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Describes the bytes the layer is over: the base version's signatures plus the layer's own edits as the last revision. Signed bytes (contents, digests, revision prefixes) are served per base version under /versions.
     */
    public CompletableFuture<DocSignaturesList200Response> list(String docId, String layerName) {
        return this.rawClient.list(docId, layerName).thenApply(response -> response.body());
    }

    /**
     * Describes the bytes the layer is over: the base version's signatures plus the layer's own edits as the last revision. Signed bytes (contents, digests, revision prefixes) are served per base version under /versions.
     */
    public CompletableFuture<DocSignaturesList200Response> list(
            String docId, String layerName, RequestOptions requestOptions) {
        return this.rawClient.list(docId, layerName, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Describes the bytes the layer is over: the base version's signatures plus the layer's own edits as the last revision. Signed bytes (contents, digests, revision prefixes) are served per base version under /versions.
     */
    public CompletableFuture<DocSignaturesList200Response> list(
            String docId, String layerName, ListSignaturesRequest request) {
        return this.rawClient.list(docId, layerName, request).thenApply(response -> response.body());
    }

    /**
     * Describes the bytes the layer is over: the base version's signatures plus the layer's own edits as the last revision. Signed bytes (contents, digests, revision prefixes) are served per base version under /versions.
     */
    public CompletableFuture<DocSignaturesList200Response> list(
            String docId, String layerName, ListSignaturesRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(docId, layerName, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesAbort200Response> abort(String docId, String layerName, String signingId) {
        return this.rawClient.abort(docId, layerName, signingId).thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesAbort200Response> abort(
            String docId, String layerName, String signingId, RequestOptions requestOptions) {
        return this.rawClient.abort(docId, layerName, signingId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesAbort200Response> abort(
            String docId, String layerName, String signingId, AbortSignaturesRequest request) {
        return this.rawClient.abort(docId, layerName, signingId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesAbort200Response> abort(
            String docId,
            String layerName,
            String signingId,
            AbortSignaturesRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .abort(docId, layerName, signingId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * <code>cms</code> is the detached CMS over the prepared digest, base64. <code>expectedVersion</code> must be what prepare returned. Idempotent by signing id: the same CMS again answers <code>already-completed</code>. Every layer of the document then sits over the new version; refetch the manifest after a completion.
     */
    public CompletableFuture<DocSignaturesComplete200Response> complete(
            String docId, String layerName, String signingId, DocSignaturesCompleteRequest request) {
        return this.rawClient.complete(docId, layerName, signingId, request).thenApply(response -> response.body());
    }

    /**
     * <code>cms</code> is the detached CMS over the prepared digest, base64. <code>expectedVersion</code> must be what prepare returned. Idempotent by signing id: the same CMS again answers <code>already-completed</code>. Every layer of the document then sits over the new version; refetch the manifest after a completion.
     */
    public CompletableFuture<DocSignaturesComplete200Response> complete(
            String docId,
            String layerName,
            String signingId,
            DocSignaturesCompleteRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .complete(docId, layerName, signingId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * Exactly one of <code>since.signature=&lt;index&gt;</code> or <code>since.revision=&lt;index&gt;</code>; the layer's pending edits are the end. <code>level=fill|annotate|lta|none</code> evaluates exploratorily and never becomes a verdict. For history between two base revisions use the version analysis.
     */
    public CompletableFuture<DocSignaturesAnalysis200Response> analysis(String docId, String layerName) {
        return this.rawClient.analysis(docId, layerName).thenApply(response -> response.body());
    }

    /**
     * Exactly one of <code>since.signature=&lt;index&gt;</code> or <code>since.revision=&lt;index&gt;</code>; the layer's pending edits are the end. <code>level=fill|annotate|lta|none</code> evaluates exploratorily and never becomes a verdict. For history between two base revisions use the version analysis.
     */
    public CompletableFuture<DocSignaturesAnalysis200Response> analysis(
            String docId, String layerName, RequestOptions requestOptions) {
        return this.rawClient.analysis(docId, layerName, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Exactly one of <code>since.signature=&lt;index&gt;</code> or <code>since.revision=&lt;index&gt;</code>; the layer's pending edits are the end. <code>level=fill|annotate|lta|none</code> evaluates exploratorily and never becomes a verdict. For history between two base revisions use the version analysis.
     */
    public CompletableFuture<DocSignaturesAnalysis200Response> analysis(
            String docId, String layerName, AnalysisSignaturesRequest request) {
        return this.rawClient.analysis(docId, layerName, request).thenApply(response -> response.body());
    }

    /**
     * Exactly one of <code>since.signature=&lt;index&gt;</code> or <code>since.revision=&lt;index&gt;</code>; the layer's pending edits are the end. <code>level=fill|annotate|lta|none</code> evaluates exploratorily and never becomes a verdict. For history between two base revisions use the version analysis.
     */
    public CompletableFuture<DocSignaturesAnalysis200Response> analysis(
            String docId, String layerName, AnalysisSignaturesRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .analysis(docId, layerName, request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * The multipart envelope: a JSON <code>body</code> part (field, subFilter, digest, contentsSize, signer, certify, lock, appearance) and an optional <code>resource:&lt;key&gt;</code> PDF part the body's <code>appearance.resource</code> names. A certification (<code>certify.permission</code>) additionally requires <code>doc.sign.certify</code>. The layer is read-only until the signing completes, is aborted, or expires (15 minutes). A layer behind the document head cannot sign (StaleBase).
     */
    public CompletableFuture<DocSignaturesPrepare200Response> prepare(
            String docId, String layerName, File file, PrepareSignaturesRequest request) {
        return this.rawClient.prepare(docId, layerName, file, request).thenApply(response -> response.body());
    }

    /**
     * The multipart envelope: a JSON <code>body</code> part (field, subFilter, digest, contentsSize, signer, certify, lock, appearance) and an optional <code>resource:&lt;key&gt;</code> PDF part the body's <code>appearance.resource</code> names. A certification (<code>certify.permission</code>) additionally requires <code>doc.sign.certify</code>. The layer is read-only until the signing completes, is aborted, or expires (15 minutes). A layer behind the document head cannot sign (StaleBase).
     */
    public CompletableFuture<DocSignaturesPrepare200Response> prepare(
            String docId,
            String layerName,
            File file,
            PrepareSignaturesRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .prepare(docId, layerName, file, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesPrepare200Response> prepare(
            String docId, String layerName, InputStream stream, String filename) {
        return this.rawClient.prepare(docId, layerName, stream, filename).thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesPrepare200Response> prepare(
            String docId, String layerName, InputStream stream, String filename, MediaType mediaType) {
        return this.rawClient
                .prepare(docId, layerName, stream, filename, mediaType)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesPrepare200Response> prepare(
            String docId, String layerName, InputStream stream, String filename, RequestOptions requestOptions) {
        return this.rawClient
                .prepare(docId, layerName, stream, filename, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DocSignaturesPrepare200Response> prepare(
            String docId,
            String layerName,
            InputStream stream,
            String filename,
            MediaType mediaType,
            RequestOptions requestOptions) {
        return this.rawClient
                .prepare(docId, layerName, stream, filename, mediaType, requestOptions)
                .thenApply(response -> response.body());
    }
}
