/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.resources.doc.annotations;

import com.cloudpdf.api.core.ClientOptions;
import com.cloudpdf.api.core.CloudpdfApiApiException;
import com.cloudpdf.api.core.CloudpdfApiException;
import com.cloudpdf.api.core.CloudpdfApiHttpResponse;
import com.cloudpdf.api.core.MediaTypes;
import com.cloudpdf.api.core.ObjectMappers;
import com.cloudpdf.api.core.RequestOptions;
import com.cloudpdf.api.core.RetryInterceptor;
import com.cloudpdf.api.errors.BadRequestError;
import com.cloudpdf.api.errors.NotFoundError;
import com.cloudpdf.api.resources.doc.annotations.requests.CreateAnnotationsRequest;
import com.cloudpdf.api.resources.doc.annotations.requests.DeleteAnnotationsRequest;
import com.cloudpdf.api.resources.doc.annotations.requests.ListAnnotationsRequest;
import com.cloudpdf.api.resources.doc.annotations.requests.UpdateAnnotationsRequest;
import com.cloudpdf.api.types.DocAnnotationsCreate200Response;
import com.cloudpdf.api.types.DocAnnotationsDelete200Response;
import com.cloudpdf.api.types.DocAnnotationsList200Response;
import com.cloudpdf.api.types.DocAnnotationsUpdate200Response;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawAnnotationsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawAnnotationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsList200Response>> list(
            String docId, String layerName, int pon) {
        return list(docId, layerName, pon, ListAnnotationsRequest.builder().build());
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsList200Response>> list(
            String docId, String layerName, int pon, RequestOptions requestOptions) {
        return list(docId, layerName, pon, ListAnnotationsRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsList200Response>> list(
            String docId, String layerName, int pon, ListAnnotationsRequest request) {
        return list(docId, layerName, pon, request, null);
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsList200Response>> list(
            String docId, String layerName, int pon, ListAnnotationsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/docs")
                .addPathSegment(docId)
                .addPathSegments("layers")
                .addPathSegment(layerName)
                .addPathSegments("annotations/pages")
                .addPathSegment(Integer.toString(pon))
                .addPathSegments("items");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        if (request.getDocumentPassword().isPresent()) {
            _requestBuilder.addHeader(
                    "X-Document-Password", request.getDocumentPassword().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsList200Response>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CloudpdfApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, DocAnnotationsList200Response.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 404) {
                            future.completeExceptionally(new NotFoundError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CloudpdfApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CloudpdfApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.
     */
    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsCreate200Response>> create(
            String docId, String layerName, int pon, Map<String, Object> body) {
        return create(
                docId,
                layerName,
                pon,
                CreateAnnotationsRequest.builder().body(body).build());
    }

    /**
     * Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.
     */
    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsCreate200Response>> create(
            String docId, String layerName, int pon, Map<String, Object> body, RequestOptions requestOptions) {
        return create(
                docId,
                layerName,
                pon,
                CreateAnnotationsRequest.builder().body(body).build(),
                requestOptions);
    }

    /**
     * Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.
     */
    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsCreate200Response>> create(
            String docId, String layerName, int pon, CreateAnnotationsRequest request) {
        return create(docId, layerName, pon, request, null);
    }

    /**
     * Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.
     */
    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsCreate200Response>> create(
            String docId, String layerName, int pon, CreateAnnotationsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/docs")
                .addPathSegment(docId)
                .addPathSegments("layers")
                .addPathSegment(layerName)
                .addPathSegments("annotations/pages")
                .addPathSegment(Integer.toString(pon))
                .addPathSegments("items");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        if (request.getDocumentPassword().isPresent()) {
            _requestBuilder.addHeader(
                    "X-Document-Password", request.getDocumentPassword().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsCreate200Response>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CloudpdfApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, DocAnnotationsCreate200Response.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CloudpdfApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CloudpdfApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsDelete200Response>> delete(
            String docId, String layerName, int pon, String annotKey) {
        return delete(
                docId,
                layerName,
                pon,
                annotKey,
                DeleteAnnotationsRequest.builder().build());
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsDelete200Response>> delete(
            String docId, String layerName, int pon, String annotKey, RequestOptions requestOptions) {
        return delete(
                docId,
                layerName,
                pon,
                annotKey,
                DeleteAnnotationsRequest.builder().build(),
                requestOptions);
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsDelete200Response>> delete(
            String docId, String layerName, int pon, String annotKey, DeleteAnnotationsRequest request) {
        return delete(docId, layerName, pon, annotKey, request, null);
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsDelete200Response>> delete(
            String docId,
            String layerName,
            int pon,
            String annotKey,
            DeleteAnnotationsRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/docs")
                .addPathSegment(docId)
                .addPathSegments("layers")
                .addPathSegment(layerName)
                .addPathSegments("annotations/pages")
                .addPathSegment(Integer.toString(pon))
                .addPathSegments("items")
                .addPathSegment(annotKey);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        if (request.getDocumentPassword().isPresent()) {
            _requestBuilder.addHeader(
                    "X-Document-Password", request.getDocumentPassword().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsDelete200Response>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CloudpdfApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, DocAnnotationsDelete200Response.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 404) {
                            future.completeExceptionally(new NotFoundError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CloudpdfApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CloudpdfApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsUpdate200Response>> update(
            String docId, String layerName, int pon, String annotKey, Map<String, Object> body) {
        return update(
                docId,
                layerName,
                pon,
                annotKey,
                UpdateAnnotationsRequest.builder().body(body).build());
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsUpdate200Response>> update(
            String docId,
            String layerName,
            int pon,
            String annotKey,
            Map<String, Object> body,
            RequestOptions requestOptions) {
        return update(
                docId,
                layerName,
                pon,
                annotKey,
                UpdateAnnotationsRequest.builder().body(body).build(),
                requestOptions);
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsUpdate200Response>> update(
            String docId, String layerName, int pon, String annotKey, UpdateAnnotationsRequest request) {
        return update(docId, layerName, pon, annotKey, request, null);
    }

    public CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsUpdate200Response>> update(
            String docId,
            String layerName,
            int pon,
            String annotKey,
            UpdateAnnotationsRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/docs")
                .addPathSegment(docId)
                .addPathSegments("layers")
                .addPathSegment(layerName)
                .addPathSegments("annotations/pages")
                .addPathSegment(Integer.toString(pon))
                .addPathSegments("items")
                .addPathSegment(annotKey);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        if (request.getDocumentPassword().isPresent()) {
            _requestBuilder.addHeader(
                    "X-Document-Password", request.getDocumentPassword().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<CloudpdfApiHttpResponse<DocAnnotationsUpdate200Response>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new CloudpdfApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, DocAnnotationsUpdate200Response.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new CloudpdfApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new CloudpdfApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CloudpdfApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
