/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class DocAnnotationsList200ResponseAnnotationsItemRedactRef {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private DocAnnotationsList200ResponseAnnotationsItemRedactRef(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static DocAnnotationsList200ResponseAnnotationsItemRedactRef objectNumber(
            DocAnnotationsList200ResponseAnnotationsItemRedactRefObjectNumber value) {
        return new DocAnnotationsList200ResponseAnnotationsItemRedactRef(new ObjectNumberValue(value));
    }

    public static DocAnnotationsList200ResponseAnnotationsItemRedactRef nm(
            DocAnnotationsList200ResponseAnnotationsItemRedactRefNm value) {
        return new DocAnnotationsList200ResponseAnnotationsItemRedactRef(new NmValue(value));
    }

    public static DocAnnotationsList200ResponseAnnotationsItemRedactRef index(
            DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex value) {
        return new DocAnnotationsList200ResponseAnnotationsItemRedactRef(new IndexValue(value));
    }

    public boolean isObjectNumber() {
        return value instanceof ObjectNumberValue;
    }

    public boolean isNm() {
        return value instanceof NmValue;
    }

    public boolean isIndex() {
        return value instanceof IndexValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<DocAnnotationsList200ResponseAnnotationsItemRedactRefObjectNumber> getObjectNumber() {
        if (isObjectNumber()) {
            return Optional.of(((ObjectNumberValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<DocAnnotationsList200ResponseAnnotationsItemRedactRefNm> getNm() {
        if (isNm()) {
            return Optional.of(((NmValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex> getIndex() {
        if (isIndex()) {
            return Optional.of(((IndexValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsList200ResponseAnnotationsItemRedactRef
                && value.equals(((DocAnnotationsList200ResponseAnnotationsItemRedactRef) other).value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitObjectNumber(DocAnnotationsList200ResponseAnnotationsItemRedactRefObjectNumber objectNumber);

        T visitNm(DocAnnotationsList200ResponseAnnotationsItemRedactRefNm nm);

        T visitIndex(DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex index);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "kind", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(ObjectNumberValue.class),
        @JsonSubTypes.Type(NmValue.class),
        @JsonSubTypes.Type(IndexValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("objectNumber")
    @JsonIgnoreProperties("kind")
    private static final class ObjectNumberValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocAnnotationsList200ResponseAnnotationsItemRedactRefObjectNumber value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ObjectNumberValue() {}

        private ObjectNumberValue(DocAnnotationsList200ResponseAnnotationsItemRedactRefObjectNumber value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitObjectNumber(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ObjectNumberValue && equalTo((ObjectNumberValue) other);
        }

        private boolean equalTo(ObjectNumberValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocAnnotationsList200ResponseAnnotationsItemRedactRef{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("nm")
    @JsonIgnoreProperties("kind")
    private static final class NmValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocAnnotationsList200ResponseAnnotationsItemRedactRefNm value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private NmValue() {}

        private NmValue(DocAnnotationsList200ResponseAnnotationsItemRedactRefNm value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitNm(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof NmValue && equalTo((NmValue) other);
        }

        private boolean equalTo(NmValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocAnnotationsList200ResponseAnnotationsItemRedactRef{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("index")
    @JsonIgnoreProperties("kind")
    private static final class IndexValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private IndexValue() {}

        private IndexValue(DocAnnotationsList200ResponseAnnotationsItemRedactRefIndex value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitIndex(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof IndexValue && equalTo((IndexValue) other);
        }

        private boolean equalTo(IndexValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocAnnotationsList200ResponseAnnotationsItemRedactRef{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("kind")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocAnnotationsList200ResponseAnnotationsItemRedactRef{" + "type: " + type + ", value: " + value
                    + "}";
        }
    }
}
