/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocAnnotationsList200ResponseAnnotationsItemSquigglyActions.Builder.class)
public final class DocAnnotationsList200ResponseAnnotationsItemSquigglyActions {
    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate> activate;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter> cursorEnter;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit> cursorExit;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown> mouseDown;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp> mouseUp;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus> focus;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur> blur;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen> pageOpen;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose> pageClose;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible> pageVisible;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible> pageInvisible;

    private final Map<String, Object> additionalProperties;

    private DocAnnotationsList200ResponseAnnotationsItemSquigglyActions(
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate> activate,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter> cursorEnter,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit> cursorExit,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown> mouseDown,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp> mouseUp,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus> focus,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur> blur,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen> pageOpen,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose> pageClose,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible> pageVisible,
            Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible> pageInvisible,
            Map<String, Object> additionalProperties) {
        this.activate = activate;
        this.cursorEnter = cursorEnter;
        this.cursorExit = cursorExit;
        this.mouseDown = mouseDown;
        this.mouseUp = mouseUp;
        this.focus = focus;
        this.blur = blur;
        this.pageOpen = pageOpen;
        this.pageClose = pageClose;
        this.pageVisible = pageVisible;
        this.pageInvisible = pageInvisible;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("activate")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate> getActivate() {
        return activate;
    }

    @JsonProperty("cursorEnter")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter> getCursorEnter() {
        return cursorEnter;
    }

    @JsonProperty("cursorExit")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit> getCursorExit() {
        return cursorExit;
    }

    @JsonProperty("mouseDown")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown> getMouseDown() {
        return mouseDown;
    }

    @JsonProperty("mouseUp")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp> getMouseUp() {
        return mouseUp;
    }

    @JsonProperty("focus")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus> getFocus() {
        return focus;
    }

    @JsonProperty("blur")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur> getBlur() {
        return blur;
    }

    @JsonProperty("pageOpen")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen> getPageOpen() {
        return pageOpen;
    }

    @JsonProperty("pageClose")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose> getPageClose() {
        return pageClose;
    }

    @JsonProperty("pageVisible")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible> getPageVisible() {
        return pageVisible;
    }

    @JsonProperty("pageInvisible")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible> getPageInvisible() {
        return pageInvisible;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsList200ResponseAnnotationsItemSquigglyActions
                && equalTo((DocAnnotationsList200ResponseAnnotationsItemSquigglyActions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocAnnotationsList200ResponseAnnotationsItemSquigglyActions other) {
        return activate.equals(other.activate)
                && cursorEnter.equals(other.cursorEnter)
                && cursorExit.equals(other.cursorExit)
                && mouseDown.equals(other.mouseDown)
                && mouseUp.equals(other.mouseUp)
                && focus.equals(other.focus)
                && blur.equals(other.blur)
                && pageOpen.equals(other.pageOpen)
                && pageClose.equals(other.pageClose)
                && pageVisible.equals(other.pageVisible)
                && pageInvisible.equals(other.pageInvisible);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.activate,
                this.cursorEnter,
                this.cursorExit,
                this.mouseDown,
                this.mouseUp,
                this.focus,
                this.blur,
                this.pageOpen,
                this.pageClose,
                this.pageVisible,
                this.pageInvisible);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate> activate =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter> cursorEnter =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit> cursorExit =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown> mouseDown =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp> mouseUp = Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus> focus = Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur> blur = Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen> pageOpen =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose> pageClose =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible> pageVisible =
                Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible> pageInvisible =
                Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DocAnnotationsList200ResponseAnnotationsItemSquigglyActions other) {
            activate(other.getActivate());
            cursorEnter(other.getCursorEnter());
            cursorExit(other.getCursorExit());
            mouseDown(other.getMouseDown());
            mouseUp(other.getMouseUp());
            focus(other.getFocus());
            blur(other.getBlur());
            pageOpen(other.getPageOpen());
            pageClose(other.getPageClose());
            pageVisible(other.getPageVisible());
            pageInvisible(other.getPageInvisible());
            return this;
        }

        @JsonSetter(value = "activate", nulls = Nulls.SKIP)
        public Builder activate(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate> activate) {
            this.activate = activate;
            return this;
        }

        public Builder activate(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate activate) {
            this.activate = Optional.ofNullable(activate);
            return this;
        }

        @JsonSetter(value = "cursorEnter", nulls = Nulls.SKIP)
        public Builder cursorEnter(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter> cursorEnter) {
            this.cursorEnter = cursorEnter;
            return this;
        }

        public Builder cursorEnter(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter cursorEnter) {
            this.cursorEnter = Optional.ofNullable(cursorEnter);
            return this;
        }

        @JsonSetter(value = "cursorExit", nulls = Nulls.SKIP)
        public Builder cursorExit(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit> cursorExit) {
            this.cursorExit = cursorExit;
            return this;
        }

        public Builder cursorExit(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit cursorExit) {
            this.cursorExit = Optional.ofNullable(cursorExit);
            return this;
        }

        @JsonSetter(value = "mouseDown", nulls = Nulls.SKIP)
        public Builder mouseDown(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown> mouseDown) {
            this.mouseDown = mouseDown;
            return this;
        }

        public Builder mouseDown(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown mouseDown) {
            this.mouseDown = Optional.ofNullable(mouseDown);
            return this;
        }

        @JsonSetter(value = "mouseUp", nulls = Nulls.SKIP)
        public Builder mouseUp(Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp> mouseUp) {
            this.mouseUp = mouseUp;
            return this;
        }

        public Builder mouseUp(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp mouseUp) {
            this.mouseUp = Optional.ofNullable(mouseUp);
            return this;
        }

        @JsonSetter(value = "focus", nulls = Nulls.SKIP)
        public Builder focus(Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus> focus) {
            this.focus = focus;
            return this;
        }

        public Builder focus(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus focus) {
            this.focus = Optional.ofNullable(focus);
            return this;
        }

        @JsonSetter(value = "blur", nulls = Nulls.SKIP)
        public Builder blur(Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur> blur) {
            this.blur = blur;
            return this;
        }

        public Builder blur(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur blur) {
            this.blur = Optional.ofNullable(blur);
            return this;
        }

        @JsonSetter(value = "pageOpen", nulls = Nulls.SKIP)
        public Builder pageOpen(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen> pageOpen) {
            this.pageOpen = pageOpen;
            return this;
        }

        public Builder pageOpen(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen pageOpen) {
            this.pageOpen = Optional.ofNullable(pageOpen);
            return this;
        }

        @JsonSetter(value = "pageClose", nulls = Nulls.SKIP)
        public Builder pageClose(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose> pageClose) {
            this.pageClose = pageClose;
            return this;
        }

        public Builder pageClose(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose pageClose) {
            this.pageClose = Optional.ofNullable(pageClose);
            return this;
        }

        @JsonSetter(value = "pageVisible", nulls = Nulls.SKIP)
        public Builder pageVisible(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible> pageVisible) {
            this.pageVisible = pageVisible;
            return this;
        }

        public Builder pageVisible(DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible pageVisible) {
            this.pageVisible = Optional.ofNullable(pageVisible);
            return this;
        }

        @JsonSetter(value = "pageInvisible", nulls = Nulls.SKIP)
        public Builder pageInvisible(
                Optional<DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible> pageInvisible) {
            this.pageInvisible = pageInvisible;
            return this;
        }

        public Builder pageInvisible(
                DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible pageInvisible) {
            this.pageInvisible = Optional.ofNullable(pageInvisible);
            return this;
        }

        public DocAnnotationsList200ResponseAnnotationsItemSquigglyActions build() {
            return new DocAnnotationsList200ResponseAnnotationsItemSquigglyActions(
                    activate,
                    cursorEnter,
                    cursorExit,
                    mouseDown,
                    mouseUp,
                    focus,
                    blur,
                    pageOpen,
                    pageClose,
                    pageVisible,
                    pageInvisible,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
