/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem {
    public static final DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem
            MALFORMED_NEXT = new DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem(
                    Value.MALFORMED_NEXT, "malformed-next");

    public static final DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem
            CYCLE_DROPPED = new DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem(
                    Value.CYCLE_DROPPED, "cycle-dropped");

    public static final DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem INCOMPLETE =
            new DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem(
                    Value.INCOMPLETE, "incomplete");

    private final Value value;

    private final String string;

    DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem
                        && this.string.equals(
                                ((DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem)
                                                other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MALFORMED_NEXT:
                return visitor.visitMalformedNext();
            case CYCLE_DROPPED:
                return visitor.visitCycleDropped();
            case INCOMPLETE:
                return visitor.visitIncomplete();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem valueOf(
            String value) {
        switch (value) {
            case "malformed-next":
                return MALFORMED_NEXT;
            case "cycle-dropped":
                return CYCLE_DROPPED;
            case "incomplete":
                return INCOMPLETE;
            default:
                return new DocAnnotationsList200ResponseAnnotationsItemFreeTextActionsPageVisibleWarningsItem(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CYCLE_DROPPED,

        MALFORMED_NEXT,

        INCOMPLETE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCycleDropped();

        T visitMalformedNext();

        T visitIncomplete();

        T visitUnknown(String unknownType);
    }
}
