/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown.Builder.class)
public final class DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown {
    private final Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root;

    private final boolean incomplete;

    private final int warningFlags;

    private final List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings;

    private final Map<String, Object> additionalProperties;

    private DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown(
            Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root,
            boolean incomplete,
            int warningFlags,
            List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings,
            Map<String, Object> additionalProperties) {
        this.root = root;
        this.incomplete = incomplete;
        this.warningFlags = warningFlags;
        this.warnings = warnings;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> getRoot() {
        if (root == null) {
            return Optional.empty();
        }
        return root;
    }

    @JsonProperty("incomplete")
    public boolean getIncomplete() {
        return incomplete;
    }

    @JsonProperty("warningFlags")
    public int getWarningFlags() {
        return warningFlags;
    }

    @JsonProperty("warnings")
    public List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> getWarnings() {
        return warnings;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("root")
    private Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> _getRoot() {
        return root;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown
                && equalTo((DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown other) {
        return root.equals(other.root)
                && incomplete == other.incomplete
                && warningFlags == other.warningFlags
                && warnings.equals(other.warnings);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.root, this.incomplete, this.warningFlags, this.warnings);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IncompleteStage builder() {
        return new Builder();
    }

    public interface IncompleteStage {
        WarningFlagsStage incomplete(boolean incomplete);

        Builder from(DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown other);
    }

    public interface WarningFlagsStage {
        _FinalStage warningFlags(int warningFlags);
    }

    public interface _FinalStage {
        DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage root(Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root);

        _FinalStage root(DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot root);

        _FinalStage root(Nullable<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root);

        _FinalStage warnings(
                List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings);

        _FinalStage addWarnings(
                DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem warnings);

        _FinalStage addAllWarnings(
                List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IncompleteStage, WarningFlagsStage, _FinalStage {
        private boolean incomplete;

        private int warningFlags;

        private List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings =
                new ArrayList<>();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root =
                Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown other) {
            root(other.getRoot());
            incomplete(other.getIncomplete());
            warningFlags(other.getWarningFlags());
            warnings(other.getWarnings());
            return this;
        }

        @java.lang.Override
        @JsonSetter("incomplete")
        public WarningFlagsStage incomplete(boolean incomplete) {
            this.incomplete = incomplete;
            return this;
        }

        @java.lang.Override
        @JsonSetter("warningFlags")
        public _FinalStage warningFlags(int warningFlags) {
            this.warningFlags = warningFlags;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllWarnings(
                List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings) {
            if (warnings != null) {
                this.warnings.addAll(warnings);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addWarnings(
                DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem warnings) {
            this.warnings.add(warnings);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "warnings", nulls = Nulls.SKIP)
        public _FinalStage warnings(
                List<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownWarningsItem> warnings) {
            this.warnings.clear();
            if (warnings != null) {
                this.warnings.addAll(warnings);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage root(
                Nullable<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root) {
            if (root.isNull()) {
                this.root = null;
            } else if (root.isEmpty()) {
                this.root = Optional.empty();
            } else {
                this.root = Optional.of(root.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage root(DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot root) {
            this.root = Optional.ofNullable(root);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "root", nulls = Nulls.SKIP)
        public _FinalStage root(
                Optional<DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDownRoot> root) {
            this.root = root;
            return this;
        }

        @java.lang.Override
        public DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown build() {
            return new DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown(
                    root, incomplete, warningFlags, warnings, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
