/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocFormsGet200ResponseFieldsItemPushbuttonActions.Builder.class)
public final class DocFormsGet200ResponseFieldsItemPushbuttonActions {
    private final Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsKeystroke> keystroke;

    private final Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsFormat> format;

    private final Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsValidate> validate;

    private final Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsCalculate> calculate;

    private final Map<String, Object> additionalProperties;

    private DocFormsGet200ResponseFieldsItemPushbuttonActions(
            Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsKeystroke> keystroke,
            Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsFormat> format,
            Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsValidate> validate,
            Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsCalculate> calculate,
            Map<String, Object> additionalProperties) {
        this.keystroke = keystroke;
        this.format = format;
        this.validate = validate;
        this.calculate = calculate;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("keystroke")
    public Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsKeystroke> getKeystroke() {
        return keystroke;
    }

    @JsonProperty("format")
    public Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsFormat> getFormat() {
        return format;
    }

    @JsonProperty("validate")
    public Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsValidate> getValidate() {
        return validate;
    }

    @JsonProperty("calculate")
    public Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsCalculate> getCalculate() {
        return calculate;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocFormsGet200ResponseFieldsItemPushbuttonActions
                && equalTo((DocFormsGet200ResponseFieldsItemPushbuttonActions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocFormsGet200ResponseFieldsItemPushbuttonActions other) {
        return keystroke.equals(other.keystroke)
                && format.equals(other.format)
                && validate.equals(other.validate)
                && calculate.equals(other.calculate);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.keystroke, this.format, this.validate, this.calculate);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsKeystroke> keystroke = Optional.empty();

        private Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsFormat> format = Optional.empty();

        private Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsValidate> validate = Optional.empty();

        private Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsCalculate> calculate = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DocFormsGet200ResponseFieldsItemPushbuttonActions other) {
            keystroke(other.getKeystroke());
            format(other.getFormat());
            validate(other.getValidate());
            calculate(other.getCalculate());
            return this;
        }

        @JsonSetter(value = "keystroke", nulls = Nulls.SKIP)
        public Builder keystroke(Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsKeystroke> keystroke) {
            this.keystroke = keystroke;
            return this;
        }

        public Builder keystroke(DocFormsGet200ResponseFieldsItemPushbuttonActionsKeystroke keystroke) {
            this.keystroke = Optional.ofNullable(keystroke);
            return this;
        }

        @JsonSetter(value = "format", nulls = Nulls.SKIP)
        public Builder format(Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsFormat> format) {
            this.format = format;
            return this;
        }

        public Builder format(DocFormsGet200ResponseFieldsItemPushbuttonActionsFormat format) {
            this.format = Optional.ofNullable(format);
            return this;
        }

        @JsonSetter(value = "validate", nulls = Nulls.SKIP)
        public Builder validate(Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsValidate> validate) {
            this.validate = validate;
            return this;
        }

        public Builder validate(DocFormsGet200ResponseFieldsItemPushbuttonActionsValidate validate) {
            this.validate = Optional.ofNullable(validate);
            return this;
        }

        @JsonSetter(value = "calculate", nulls = Nulls.SKIP)
        public Builder calculate(Optional<DocFormsGet200ResponseFieldsItemPushbuttonActionsCalculate> calculate) {
            this.calculate = calculate;
            return this;
        }

        public Builder calculate(DocFormsGet200ResponseFieldsItemPushbuttonActionsCalculate calculate) {
            this.calculate = Optional.ofNullable(calculate);
            return this;
        }

        public DocFormsGet200ResponseFieldsItemPushbuttonActions build() {
            return new DocFormsGet200ResponseFieldsItemPushbuttonActions(
                    keystroke, format, validate, calculate, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
