/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocHead200ResponseAccessReasonsItem {
    public static final DocHead200ResponseAccessReasonsItem PASSWORD =
            new DocHead200ResponseAccessReasonsItem(Value.PASSWORD, "password");

    public static final DocHead200ResponseAccessReasonsItem CDN =
            new DocHead200ResponseAccessReasonsItem(Value.CDN, "cdn");

    public static final DocHead200ResponseAccessReasonsItem PERMISSIONS_UNKNOWN =
            new DocHead200ResponseAccessReasonsItem(Value.PERMISSIONS_UNKNOWN, "permissions-unknown");

    private final Value value;

    private final String string;

    DocHead200ResponseAccessReasonsItem(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocHead200ResponseAccessReasonsItem
                        && this.string.equals(((DocHead200ResponseAccessReasonsItem) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PASSWORD:
                return visitor.visitPassword();
            case CDN:
                return visitor.visitCdn();
            case PERMISSIONS_UNKNOWN:
                return visitor.visitPermissionsUnknown();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocHead200ResponseAccessReasonsItem valueOf(String value) {
        switch (value) {
            case "password":
                return PASSWORD;
            case "cdn":
                return CDN;
            case "permissions-unknown":
                return PERMISSIONS_UNKNOWN;
            default:
                return new DocHead200ResponseAccessReasonsItem(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PASSWORD,

        CDN,

        PERMISSIONS_UNKNOWN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPassword();

        T visitCdn();

        T visitPermissionsUnknown();

        T visitUnknown(String unknownType);
    }
}
