/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode {
    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode DARKEN =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.DARKEN, "darken");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode COLOR =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.COLOR, "color");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode LIGHTEN =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.LIGHTEN, "lighten");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode EXCLUSION =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.EXCLUSION, "exclusion");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode LUMINOSITY =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.LUMINOSITY, "luminosity");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode COLOR_BURN =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.COLOR_BURN, "color-burn");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode DIFFERENCE =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.DIFFERENCE, "difference");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode MULTIPLY =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.MULTIPLY, "multiply");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode OVERLAY =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.OVERLAY, "overlay");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode HARD_LIGHT =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.HARD_LIGHT, "hard-light");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode HUE =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.HUE, "hue");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode SCREEN =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.SCREEN, "screen");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode COLOR_DODGE =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.COLOR_DODGE, "color-dodge");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode SOFT_LIGHT =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.SOFT_LIGHT, "soft-light");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode NORMAL =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.NORMAL, "normal");

    public static final DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode SATURATION =
            new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.SATURATION, "saturation");

    private final Value value;

    private final String string;

    DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode
                        && this.string.equals(
                                ((DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DARKEN:
                return visitor.visitDarken();
            case COLOR:
                return visitor.visitColor();
            case LIGHTEN:
                return visitor.visitLighten();
            case EXCLUSION:
                return visitor.visitExclusion();
            case LUMINOSITY:
                return visitor.visitLuminosity();
            case COLOR_BURN:
                return visitor.visitColorBurn();
            case DIFFERENCE:
                return visitor.visitDifference();
            case MULTIPLY:
                return visitor.visitMultiply();
            case OVERLAY:
                return visitor.visitOverlay();
            case HARD_LIGHT:
                return visitor.visitHardLight();
            case HUE:
                return visitor.visitHue();
            case SCREEN:
                return visitor.visitScreen();
            case COLOR_DODGE:
                return visitor.visitColorDodge();
            case SOFT_LIGHT:
                return visitor.visitSoftLight();
            case NORMAL:
                return visitor.visitNormal();
            case SATURATION:
                return visitor.visitSaturation();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode valueOf(String value) {
        switch (value) {
            case "darken":
                return DARKEN;
            case "color":
                return COLOR;
            case "lighten":
                return LIGHTEN;
            case "exclusion":
                return EXCLUSION;
            case "luminosity":
                return LUMINOSITY;
            case "color-burn":
                return COLOR_BURN;
            case "difference":
                return DIFFERENCE;
            case "multiply":
                return MULTIPLY;
            case "overlay":
                return OVERLAY;
            case "hard-light":
                return HARD_LIGHT;
            case "hue":
                return HUE;
            case "screen":
                return SCREEN;
            case "color-dodge":
                return COLOR_DODGE;
            case "soft-light":
                return SOFT_LIGHT;
            case "normal":
                return NORMAL;
            case "saturation":
                return SATURATION;
            default:
                return new DocAnnotationsList200ResponseAnnotationsItemCircleBlendMode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NORMAL,

        MULTIPLY,

        SCREEN,

        OVERLAY,

        DARKEN,

        LIGHTEN,

        COLOR_DODGE,

        COLOR_BURN,

        HARD_LIGHT,

        SOFT_LIGHT,

        DIFFERENCE,

        EXCLUSION,

        HUE,

        SATURATION,

        COLOR,

        LUMINOSITY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNormal();

        T visitMultiply();

        T visitScreen();

        T visitOverlay();

        T visitDarken();

        T visitLighten();

        T visitColorDodge();

        T visitColorBurn();

        T visitHardLight();

        T visitSoftLight();

        T visitDifference();

        T visitExclusion();

        T visitHue();

        T visitSaturation();

        T visitColor();

        T visitLuminosity();

        T visitUnknown(String unknownType);
    }
}
