/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir {
    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir LTR =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir(Value.LTR, "ltr");

    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir RTL =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir(Value.RTL, "rtl");

    private final Value value;

    private final String string;

    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir
                        && this.string.equals(
                                ((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir)
                                                other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LTR:
                return visitor.visitLtr();
            case RTL:
                return visitor.visitRtl();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir valueOf(
            String value) {
        switch (value) {
            case "ltr":
                return LTR;
            case "rtl":
                return RTL;
            default:
                return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LTR,

        RTL,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLtr();

        T visitRtl();

        T visitUnknown(String unknownType);
    }
}
