/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality {
    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality DURABLE =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality(
                    Value.DURABLE, "durable");

    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality WEAK =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality(Value.WEAK, "weak");

    private final Value value;

    private final String string;

    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality
                        && this.string.equals(
                                ((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality)
                                                other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DURABLE:
                return visitor.visitDurable();
            case WEAK:
                return visitor.visitWeak();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality valueOf(
            String value) {
        switch (value) {
            case "durable":
                return DURABLE;
            case "weak":
                return WEAK;
            default:
                return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DURABLE,

        WEAK,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDurable();

        T visitWeak();

        T visitUnknown(String unknownType);
    }
}
