/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions.Builder.class)
public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions {
    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate> activate;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter> cursorEnter;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit> cursorExit;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown> mouseDown;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp> mouseUp;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus> focus;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur> blur;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen> pageOpen;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose> pageClose;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible> pageVisible;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible>
            pageInvisible;

    private final Map<String, Object> additionalProperties;

    private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions(
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate> activate,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter> cursorEnter,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit> cursorExit,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown> mouseDown,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp> mouseUp,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus> focus,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur> blur,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen> pageOpen,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose> pageClose,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible> pageVisible,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible> pageInvisible,
            Map<String, Object> additionalProperties) {
        this.activate = activate;
        this.cursorEnter = cursorEnter;
        this.cursorExit = cursorExit;
        this.mouseDown = mouseDown;
        this.mouseUp = mouseUp;
        this.focus = focus;
        this.blur = blur;
        this.pageOpen = pageOpen;
        this.pageClose = pageClose;
        this.pageVisible = pageVisible;
        this.pageInvisible = pageInvisible;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("activate")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate> getActivate() {
        return activate;
    }

    @JsonProperty("cursorEnter")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter> getCursorEnter() {
        return cursorEnter;
    }

    @JsonProperty("cursorExit")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit> getCursorExit() {
        return cursorExit;
    }

    @JsonProperty("mouseDown")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown> getMouseDown() {
        return mouseDown;
    }

    @JsonProperty("mouseUp")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp> getMouseUp() {
        return mouseUp;
    }

    @JsonProperty("focus")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus> getFocus() {
        return focus;
    }

    @JsonProperty("blur")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur> getBlur() {
        return blur;
    }

    @JsonProperty("pageOpen")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen> getPageOpen() {
        return pageOpen;
    }

    @JsonProperty("pageClose")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose> getPageClose() {
        return pageClose;
    }

    @JsonProperty("pageVisible")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible> getPageVisible() {
        return pageVisible;
    }

    @JsonProperty("pageInvisible")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible>
            getPageInvisible() {
        return pageInvisible;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions
                && equalTo((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions other) {
        return activate.equals(other.activate)
                && cursorEnter.equals(other.cursorEnter)
                && cursorExit.equals(other.cursorExit)
                && mouseDown.equals(other.mouseDown)
                && mouseUp.equals(other.mouseUp)
                && focus.equals(other.focus)
                && blur.equals(other.blur)
                && pageOpen.equals(other.pageOpen)
                && pageClose.equals(other.pageClose)
                && pageVisible.equals(other.pageVisible)
                && pageInvisible.equals(other.pageInvisible);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.activate,
                this.cursorEnter,
                this.cursorExit,
                this.mouseDown,
                this.mouseUp,
                this.focus,
                this.blur,
                this.pageOpen,
                this.pageClose,
                this.pageVisible,
                this.pageInvisible);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate> activate =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter> cursorEnter =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit> cursorExit =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown> mouseDown =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp> mouseUp =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus> focus =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur> blur =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen> pageOpen =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose> pageClose =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible> pageVisible =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible>
                pageInvisible = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions other) {
            activate(other.getActivate());
            cursorEnter(other.getCursorEnter());
            cursorExit(other.getCursorExit());
            mouseDown(other.getMouseDown());
            mouseUp(other.getMouseUp());
            focus(other.getFocus());
            blur(other.getBlur());
            pageOpen(other.getPageOpen());
            pageClose(other.getPageClose());
            pageVisible(other.getPageVisible());
            pageInvisible(other.getPageInvisible());
            return this;
        }

        @JsonSetter(value = "activate", nulls = Nulls.SKIP)
        public Builder activate(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate> activate) {
            this.activate = activate;
            return this;
        }

        public Builder activate(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate activate) {
            this.activate = Optional.ofNullable(activate);
            return this;
        }

        @JsonSetter(value = "cursorEnter", nulls = Nulls.SKIP)
        public Builder cursorEnter(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter> cursorEnter) {
            this.cursorEnter = cursorEnter;
            return this;
        }

        public Builder cursorEnter(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter cursorEnter) {
            this.cursorEnter = Optional.ofNullable(cursorEnter);
            return this;
        }

        @JsonSetter(value = "cursorExit", nulls = Nulls.SKIP)
        public Builder cursorExit(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit> cursorExit) {
            this.cursorExit = cursorExit;
            return this;
        }

        public Builder cursorExit(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit cursorExit) {
            this.cursorExit = Optional.ofNullable(cursorExit);
            return this;
        }

        @JsonSetter(value = "mouseDown", nulls = Nulls.SKIP)
        public Builder mouseDown(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown> mouseDown) {
            this.mouseDown = mouseDown;
            return this;
        }

        public Builder mouseDown(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown mouseDown) {
            this.mouseDown = Optional.ofNullable(mouseDown);
            return this;
        }

        @JsonSetter(value = "mouseUp", nulls = Nulls.SKIP)
        public Builder mouseUp(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp> mouseUp) {
            this.mouseUp = mouseUp;
            return this;
        }

        public Builder mouseUp(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp mouseUp) {
            this.mouseUp = Optional.ofNullable(mouseUp);
            return this;
        }

        @JsonSetter(value = "focus", nulls = Nulls.SKIP)
        public Builder focus(Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus> focus) {
            this.focus = focus;
            return this;
        }

        public Builder focus(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus focus) {
            this.focus = Optional.ofNullable(focus);
            return this;
        }

        @JsonSetter(value = "blur", nulls = Nulls.SKIP)
        public Builder blur(Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur> blur) {
            this.blur = blur;
            return this;
        }

        public Builder blur(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur blur) {
            this.blur = Optional.ofNullable(blur);
            return this;
        }

        @JsonSetter(value = "pageOpen", nulls = Nulls.SKIP)
        public Builder pageOpen(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen> pageOpen) {
            this.pageOpen = pageOpen;
            return this;
        }

        public Builder pageOpen(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen pageOpen) {
            this.pageOpen = Optional.ofNullable(pageOpen);
            return this;
        }

        @JsonSetter(value = "pageClose", nulls = Nulls.SKIP)
        public Builder pageClose(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose> pageClose) {
            this.pageClose = pageClose;
            return this;
        }

        public Builder pageClose(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose pageClose) {
            this.pageClose = Optional.ofNullable(pageClose);
            return this;
        }

        @JsonSetter(value = "pageVisible", nulls = Nulls.SKIP)
        public Builder pageVisible(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible> pageVisible) {
            this.pageVisible = pageVisible;
            return this;
        }

        public Builder pageVisible(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible pageVisible) {
            this.pageVisible = Optional.ofNullable(pageVisible);
            return this;
        }

        @JsonSetter(value = "pageInvisible", nulls = Nulls.SKIP)
        public Builder pageInvisible(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible>
                        pageInvisible) {
            this.pageInvisible = pageInvisible;
            return this;
        }

        public Builder pageInvisible(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible pageInvisible) {
            this.pageInvisible = Optional.ofNullable(pageInvisible);
            return this;
        }

        public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions build() {
            return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions(
                    activate,
                    cursorEnter,
                    cursorExit,
                    mouseDown,
                    mouseUp,
                    focus,
                    blur,
                    pageOpen,
                    pageClose,
                    pageVisible,
                    pageInvisible,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
