/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsDelete404ResponseCode {
    public static final DocAnnotationsDelete404ResponseCode MALFORMED_PDF =
            new DocAnnotationsDelete404ResponseCode(Value.MALFORMED_PDF, "MalformedPdf");

    public static final DocAnnotationsDelete404ResponseCode UNKNOWN =
            new DocAnnotationsDelete404ResponseCode(Value.UNKNOWN, "Unknown");

    public static final DocAnnotationsDelete404ResponseCode WEAK_ANNOTATION_SESSION_CONFLICT =
            new DocAnnotationsDelete404ResponseCode(
                    Value.WEAK_ANNOTATION_SESSION_CONFLICT, "WeakAnnotationSessionConflict");

    public static final DocAnnotationsDelete404ResponseCode WIRE_FORMAT =
            new DocAnnotationsDelete404ResponseCode(Value.WIRE_FORMAT, "WireFormat");

    public static final DocAnnotationsDelete404ResponseCode RUNTIME_UNAVAILABLE =
            new DocAnnotationsDelete404ResponseCode(Value.RUNTIME_UNAVAILABLE, "RuntimeUnavailable");

    public static final DocAnnotationsDelete404ResponseCode UNAUTHENTICATED =
            new DocAnnotationsDelete404ResponseCode(Value.UNAUTHENTICATED, "Unauthenticated");

    public static final DocAnnotationsDelete404ResponseCode FORBIDDEN =
            new DocAnnotationsDelete404ResponseCode(Value.FORBIDDEN, "Forbidden");

    public static final DocAnnotationsDelete404ResponseCode DOC_OPEN_FAILED =
            new DocAnnotationsDelete404ResponseCode(Value.DOC_OPEN_FAILED, "DocOpenFailed");

    public static final DocAnnotationsDelete404ResponseCode NOT_FOUND =
            new DocAnnotationsDelete404ResponseCode(Value.NOT_FOUND, "NotFound");

    public static final DocAnnotationsDelete404ResponseCode ABORTED =
            new DocAnnotationsDelete404ResponseCode(Value.ABORTED, "Aborted");

    public static final DocAnnotationsDelete404ResponseCode DOC_PASSWORD_REQUIRED =
            new DocAnnotationsDelete404ResponseCode(Value.DOC_PASSWORD_REQUIRED, "DocPasswordRequired");

    public static final DocAnnotationsDelete404ResponseCode INVALID_ARG =
            new DocAnnotationsDelete404ResponseCode(Value.INVALID_ARG, "InvalidArg");

    public static final DocAnnotationsDelete404ResponseCode NETWORK =
            new DocAnnotationsDelete404ResponseCode(Value.NETWORK, "Network");

    public static final DocAnnotationsDelete404ResponseCode INVALID_REFERENCE =
            new DocAnnotationsDelete404ResponseCode(Value.INVALID_REFERENCE, "InvalidReference");

    public static final DocAnnotationsDelete404ResponseCode DOC_PASSWORD_INCORRECT =
            new DocAnnotationsDelete404ResponseCode(Value.DOC_PASSWORD_INCORRECT, "DocPasswordIncorrect");

    public static final DocAnnotationsDelete404ResponseCode DOC_NOT_OPEN =
            new DocAnnotationsDelete404ResponseCode(Value.DOC_NOT_OPEN, "DocNotOpen");

    public static final DocAnnotationsDelete404ResponseCode LAYER_VERSION_CONFLICT =
            new DocAnnotationsDelete404ResponseCode(Value.LAYER_VERSION_CONFLICT, "LayerVersionConflict");

    public static final DocAnnotationsDelete404ResponseCode NOT_IMPLEMENTED =
            new DocAnnotationsDelete404ResponseCode(Value.NOT_IMPLEMENTED, "NotImplemented");

    private final Value value;

    private final String string;

    DocAnnotationsDelete404ResponseCode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsDelete404ResponseCode
                        && this.string.equals(((DocAnnotationsDelete404ResponseCode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MALFORMED_PDF:
                return visitor.visitMalformedPdf();
            case UNKNOWN:
                return visitor.visitUnknown();
            case WEAK_ANNOTATION_SESSION_CONFLICT:
                return visitor.visitWeakAnnotationSessionConflict();
            case WIRE_FORMAT:
                return visitor.visitWireFormat();
            case RUNTIME_UNAVAILABLE:
                return visitor.visitRuntimeUnavailable();
            case UNAUTHENTICATED:
                return visitor.visitUnauthenticated();
            case FORBIDDEN:
                return visitor.visitForbidden();
            case DOC_OPEN_FAILED:
                return visitor.visitDocOpenFailed();
            case NOT_FOUND:
                return visitor.visitNotFound();
            case ABORTED:
                return visitor.visitAborted();
            case DOC_PASSWORD_REQUIRED:
                return visitor.visitDocPasswordRequired();
            case INVALID_ARG:
                return visitor.visitInvalidArg();
            case NETWORK:
                return visitor.visitNetwork();
            case INVALID_REFERENCE:
                return visitor.visitInvalidReference();
            case DOC_PASSWORD_INCORRECT:
                return visitor.visitDocPasswordIncorrect();
            case DOC_NOT_OPEN:
                return visitor.visitDocNotOpen();
            case LAYER_VERSION_CONFLICT:
                return visitor.visitLayerVersionConflict();
            case NOT_IMPLEMENTED:
                return visitor.visitNotImplemented();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsDelete404ResponseCode valueOf(String value) {
        switch (value) {
            case "MalformedPdf":
                return MALFORMED_PDF;
            case "Unknown":
                return UNKNOWN;
            case "WeakAnnotationSessionConflict":
                return WEAK_ANNOTATION_SESSION_CONFLICT;
            case "WireFormat":
                return WIRE_FORMAT;
            case "RuntimeUnavailable":
                return RUNTIME_UNAVAILABLE;
            case "Unauthenticated":
                return UNAUTHENTICATED;
            case "Forbidden":
                return FORBIDDEN;
            case "DocOpenFailed":
                return DOC_OPEN_FAILED;
            case "NotFound":
                return NOT_FOUND;
            case "Aborted":
                return ABORTED;
            case "DocPasswordRequired":
                return DOC_PASSWORD_REQUIRED;
            case "InvalidArg":
                return INVALID_ARG;
            case "Network":
                return NETWORK;
            case "InvalidReference":
                return INVALID_REFERENCE;
            case "DocPasswordIncorrect":
                return DOC_PASSWORD_INCORRECT;
            case "DocNotOpen":
                return DOC_NOT_OPEN;
            case "LayerVersionConflict":
                return LAYER_VERSION_CONFLICT;
            case "NotImplemented":
                return NOT_IMPLEMENTED;
            default:
                return new DocAnnotationsDelete404ResponseCode(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        UNKNOWN,

        INVALID_ARG,

        DOC_NOT_OPEN,

        DOC_OPEN_FAILED,

        DOC_PASSWORD_REQUIRED,

        DOC_PASSWORD_INCORRECT,

        ABORTED,

        NETWORK,

        UNAUTHENTICATED,

        FORBIDDEN,

        NOT_FOUND,

        WIRE_FORMAT,

        RUNTIME_UNAVAILABLE,

        INVALID_REFERENCE,

        WEAK_ANNOTATION_SESSION_CONFLICT,

        LAYER_VERSION_CONFLICT,

        NOT_IMPLEMENTED,

        MALFORMED_PDF,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnknown();

        T visitInvalidArg();

        T visitDocNotOpen();

        T visitDocOpenFailed();

        T visitDocPasswordRequired();

        T visitDocPasswordIncorrect();

        T visitAborted();

        T visitNetwork();

        T visitUnauthenticated();

        T visitForbidden();

        T visitNotFound();

        T visitWireFormat();

        T visitRuntimeUnavailable();

        T visitInvalidReference();

        T visitWeakAnnotationSessionConflict();

        T visitLayerVersionConflict();

        T visitNotImplemented();

        T visitMalformedPdf();

        T visitUnknown(String unknownType);
    }
}
