/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction {
    public static final DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction TRUNCATE =
            new DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction(Value.TRUNCATE, "truncate");

    public static final DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction DECIMAL =
            new DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction(Value.DECIMAL, "decimal");

    public static final DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction ROUND =
            new DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction(Value.ROUND, "round");

    public static final DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction FRACTION =
            new DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction(Value.FRACTION, "fraction");

    private final Value value;

    private final String string;

    DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction
                        && this.string.equals(
                                ((DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction) other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TRUNCATE:
                return visitor.visitTruncate();
            case DECIMAL:
                return visitor.visitDecimal();
            case ROUND:
                return visitor.visitRound();
            case FRACTION:
                return visitor.visitFraction();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction valueOf(String value) {
        switch (value) {
            case "truncate":
                return TRUNCATE;
            case "decimal":
                return DECIMAL;
            case "round":
                return ROUND;
            case "fraction":
                return FRACTION;
            default:
                return new DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlAreaItemFraction(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DECIMAL,

        FRACTION,

        ROUND,

        TRUNCATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDecimal();

        T visitFraction();

        T visitRound();

        T visitTruncate();

        T visitUnknown(String unknownType);
    }
}
