/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType {
    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType UNKNOWN =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.UNKNOWN, "unknown");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType NAMED =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.NAMED, "named");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType GOTO =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.GOTO, "goto");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType GOTO_EMBEDDED =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.GOTO_EMBEDDED, "goto-embedded");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType JAVASCRIPT =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.JAVASCRIPT, "javascript");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType SOUND =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.SOUND, "sound");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType RENDITION =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.RENDITION, "rendition");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType GOTO_REMOTE =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.GOTO_REMOTE, "goto-remote");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType LAUNCH =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.LAUNCH, "launch");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType IMPORT_DATA =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.IMPORT_DATA, "import-data");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType SET_OCG_STATE =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.SET_OCG_STATE, "set-ocg-state");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType URI =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.URI, "uri");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType MOVIE =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.MOVIE, "movie");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType SUBMIT_FORM =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.SUBMIT_FORM, "submit-form");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType HIDE =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.HIDE, "hide");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType THREAD =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value.THREAD, "thread");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType GOTO3D_VIEW =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.GOTO3D_VIEW, "goto-3d-view");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType TRANSITION =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.TRANSITION, "transition");

    public static final DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType RESET_FORM =
            new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                    Value.RESET_FORM, "reset-form");

    private final Value value;

    private final String string;

    DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType
                        && this.string.equals(
                                ((DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType) other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UNKNOWN:
                return visitor.visitUnknown();
            case NAMED:
                return visitor.visitNamed();
            case GOTO:
                return visitor.visitGoto();
            case GOTO_EMBEDDED:
                return visitor.visitGotoEmbedded();
            case JAVASCRIPT:
                return visitor.visitJavascript();
            case SOUND:
                return visitor.visitSound();
            case RENDITION:
                return visitor.visitRendition();
            case GOTO_REMOTE:
                return visitor.visitGotoRemote();
            case LAUNCH:
                return visitor.visitLaunch();
            case IMPORT_DATA:
                return visitor.visitImportData();
            case SET_OCG_STATE:
                return visitor.visitSetOcgState();
            case URI:
                return visitor.visitUri();
            case MOVIE:
                return visitor.visitMovie();
            case SUBMIT_FORM:
                return visitor.visitSubmitForm();
            case HIDE:
                return visitor.visitHide();
            case THREAD:
                return visitor.visitThread();
            case GOTO3D_VIEW:
                return visitor.visitGoto3DView();
            case TRANSITION:
                return visitor.visitTransition();
            case RESET_FORM:
                return visitor.visitResetForm();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType valueOf(String value) {
        switch (value) {
            case "unknown":
                return UNKNOWN;
            case "named":
                return NAMED;
            case "goto":
                return GOTO;
            case "goto-embedded":
                return GOTO_EMBEDDED;
            case "javascript":
                return JAVASCRIPT;
            case "sound":
                return SOUND;
            case "rendition":
                return RENDITION;
            case "goto-remote":
                return GOTO_REMOTE;
            case "launch":
                return LAUNCH;
            case "import-data":
                return IMPORT_DATA;
            case "set-ocg-state":
                return SET_OCG_STATE;
            case "uri":
                return URI;
            case "movie":
                return MOVIE;
            case "submit-form":
                return SUBMIT_FORM;
            case "hide":
                return HIDE;
            case "thread":
                return THREAD;
            case "goto-3d-view":
                return GOTO3D_VIEW;
            case "transition":
                return TRANSITION;
            case "reset-form":
                return RESET_FORM;
            default:
                return new DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDownRootType(
                        Value._UNKNOWN, value);
        }
    }

    public enum Value {
        UNKNOWN,

        GOTO,

        GOTO_REMOTE,

        GOTO_EMBEDDED,

        LAUNCH,

        THREAD,

        URI,

        SOUND,

        MOVIE,

        HIDE,

        NAMED,

        SUBMIT_FORM,

        RESET_FORM,

        IMPORT_DATA,

        JAVASCRIPT,

        SET_OCG_STATE,

        RENDITION,

        TRANSITION,

        GOTO3D_VIEW,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnknown();

        T visitGoto();

        T visitGotoRemote();

        T visitGotoEmbedded();

        T visitLaunch();

        T visitThread();

        T visitUri();

        T visitSound();

        T visitMovie();

        T visitHide();

        T visitNamed();

        T visitSubmitForm();

        T visitResetForm();

        T visitImportData();

        T visitJavascript();

        T visitSetOcgState();

        T visitRendition();

        T visitTransition();

        T visitGoto3DView();

        T visitUnknown(String unknownType);
    }
}
