/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final
class DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem {
    public static final
    DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem WORD =
            new DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem(
                    Value.WORD, "word");

    public static final
    DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem UNDERLINE =
            new DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem(
                    Value.UNDERLINE, "underline");

    public static final
    DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem LINE_THROUGH =
            new DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem(
                    Value.LINE_THROUGH, "line-through");

    private final Value value;

    private final String string;

    DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem(
            Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other
                                instanceof
                                DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem
                        && this.string.equals(
                                ((DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem)
                                                other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WORD:
                return visitor.visitWord();
            case UNDERLINE:
                return visitor.visitUnderline();
            case LINE_THROUGH:
                return visitor.visitLineThrough();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem
            valueOf(String value) {
        switch (value) {
            case "word":
                return WORD;
            case "underline":
                return UNDERLINE;
            case "line-through":
                return LINE_THROUGH;
            default:
                return new DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        UNDERLINE,

        LINE_THROUGH,

        WORD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnderline();

        T visitLineThrough();

        T visitWord();

        T visitUnknown(String unknownType);
    }
}
