/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition {
    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition
            PREFIX = new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition(
                    Value.PREFIX, "prefix");

    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition
            SUFFIX = new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition(
                    Value.SUFFIX, "suffix");

    private final Value value;

    private final String string;

    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition(
            Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other
                                instanceof
                                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition
                        && this.string.equals(
                                ((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition)
                                                other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PREFIX:
                return visitor.visitPrefix();
            case SUFFIX:
                return visitor.visitSuffix();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition valueOf(
            String value) {
        switch (value) {
            case "prefix":
                return PREFIX;
            case "suffix":
                return SUFFIX;
            default:
                return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlXItemLabelPosition(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SUFFIX,

        PREFIX,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSuffix();

        T visitPrefix();

        T visitUnknown(String unknownType);
    }
}
