/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle {
    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle INSET =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle(Value.INSET, "inset");

    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle BEVELED =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle(Value.BEVELED, "beveled");

    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle SOLID =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle(Value.SOLID, "solid");

    public static final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle DASHED =
            new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle(Value.DASHED, "dashed");

    private final Value value;

    private final String string;

    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle
                        && this.string.equals(
                                ((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle) other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case INSET:
                return visitor.visitInset();
            case BEVELED:
                return visitor.visitBeveled();
            case SOLID:
                return visitor.visitSolid();
            case DASHED:
                return visitor.visitDashed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle valueOf(String value) {
        switch (value) {
            case "inset":
                return INSET;
            case "beveled":
                return BEVELED;
            case "solid":
                return SOLID;
            case "dashed":
                return DASHED;
            default:
                return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleBorderStyle(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SOLID,

        DASHED,

        BEVELED,

        INSET,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSolid();

        T visitDashed();

        T visitBeveled();

        T visitInset();

        T visitUnknown(String unknownType);
    }
}
