/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch.Builder.class)
public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch {
    private final String path;

    private final Map<String, Object> additionalProperties;

    private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch(
            String path, Map<String, Object> additionalProperties) {
        this.path = path;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("path")
    public String getPath() {
        return path;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch
                && equalTo((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch other) {
        return path.equals(other.path);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.path);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PathStage builder() {
        return new Builder();
    }

    public interface PathStage {
        _FinalStage path(@NotNull String path);

        Builder from(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch other);
    }

    public interface _FinalStage {
        DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PathStage, _FinalStage {
        private String path;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch other) {
            path(other.getPath());
            return this;
        }

        @java.lang.Override
        @JsonSetter("path")
        public _FinalStage path(@NotNull String path) {
            this.path = Objects.requireNonNull(path, "path must not be null");
            return this;
        }

        @java.lang.Override
        public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch build() {
            return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetLaunch(
                    path, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
