/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocAnnotationsList200ResponseAnnotationsItemLineIntent {
    public static final DocAnnotationsList200ResponseAnnotationsItemLineIntent LINE_ARROW =
            new DocAnnotationsList200ResponseAnnotationsItemLineIntent(Value.LINE_ARROW, "LineArrow");

    public static final DocAnnotationsList200ResponseAnnotationsItemLineIntent LINE_DIMENSION =
            new DocAnnotationsList200ResponseAnnotationsItemLineIntent(Value.LINE_DIMENSION, "LineDimension");

    private final Value value;

    private final String string;

    DocAnnotationsList200ResponseAnnotationsItemLineIntent(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocAnnotationsList200ResponseAnnotationsItemLineIntent
                        && this.string.equals(((DocAnnotationsList200ResponseAnnotationsItemLineIntent) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LINE_ARROW:
                return visitor.visitLineArrow();
            case LINE_DIMENSION:
                return visitor.visitLineDimension();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocAnnotationsList200ResponseAnnotationsItemLineIntent valueOf(String value) {
        switch (value) {
            case "LineArrow":
                return LINE_ARROW;
            case "LineDimension":
                return LINE_DIMENSION;
            default:
                return new DocAnnotationsList200ResponseAnnotationsItemLineIntent(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LINE_ARROW,

        LINE_DIMENSION,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLineArrow();

        T visitLineDimension();

        T visitUnknown(String unknownType);
    }
}
