/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp.Builder.class)
public final class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp {
    private final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef ref;

    private final int pageObjectNumber;

    private final int index;

    private final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampIdentityQuality identityQuality;

    private final Optional<String> nm;

    private final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampFlags flags;

    private final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRect rect;

    private final Optional<String> contents;

    private final Optional<String> subject;

    private final Optional<String> author;

    private final Optional<OffsetDateTime> created;

    private final Optional<OffsetDateTime> modified;

    private final DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampBlendMode blendMode;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType;

    private final Optional<String> userId;

    private final Optional<String> groupId;

    private final Optional<String> createdBy;

    private final Optional<String> updatedBy;

    private final Optional<PdfAnnotationActions> actions;

    private final Optional<String> name;

    private final Optional<Double> rotation;

    private final Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect> unrotatedRect;

    private final Map<String, Object> additionalProperties;

    private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp(
            DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef ref,
            int pageObjectNumber,
            int index,
            DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampIdentityQuality identityQuality,
            Optional<String> nm,
            DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampFlags flags,
            DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRect rect,
            Optional<String> contents,
            Optional<String> subject,
            Optional<String> author,
            Optional<OffsetDateTime> created,
            Optional<OffsetDateTime> modified,
            DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampBlendMode blendMode,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType,
            Optional<String> userId,
            Optional<String> groupId,
            Optional<String> createdBy,
            Optional<String> updatedBy,
            Optional<PdfAnnotationActions> actions,
            Optional<String> name,
            Optional<Double> rotation,
            Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect> unrotatedRect,
            Map<String, Object> additionalProperties) {
        this.ref = ref;
        this.pageObjectNumber = pageObjectNumber;
        this.index = index;
        this.identityQuality = identityQuality;
        this.nm = nm;
        this.flags = flags;
        this.rect = rect;
        this.contents = contents;
        this.subject = subject;
        this.author = author;
        this.created = created;
        this.modified = modified;
        this.blendMode = blendMode;
        this.inReplyTo = inReplyTo;
        this.replyType = replyType;
        this.userId = userId;
        this.groupId = groupId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.actions = actions;
        this.name = name;
        this.rotation = rotation;
        this.unrotatedRect = unrotatedRect;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("ref")
    public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef getRef() {
        return ref;
    }

    @JsonProperty("pageObjectNumber")
    public int getPageObjectNumber() {
        return pageObjectNumber;
    }

    @JsonProperty("index")
    public int getIndex() {
        return index;
    }

    @JsonProperty("identityQuality")
    public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampIdentityQuality getIdentityQuality() {
        return identityQuality;
    }

    @JsonIgnore
    public Optional<String> getNm() {
        if (nm == null) {
            return Optional.empty();
        }
        return nm;
    }

    @JsonProperty("flags")
    public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampFlags getFlags() {
        return flags;
    }

    @JsonProperty("rect")
    public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRect getRect() {
        return rect;
    }

    @JsonIgnore
    public Optional<String> getContents() {
        if (contents == null) {
            return Optional.empty();
        }
        return contents;
    }

    @JsonIgnore
    public Optional<String> getSubject() {
        if (subject == null) {
            return Optional.empty();
        }
        return subject;
    }

    @JsonIgnore
    public Optional<String> getAuthor() {
        if (author == null) {
            return Optional.empty();
        }
        return author;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getCreated() {
        if (created == null) {
            return Optional.empty();
        }
        return created;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getModified() {
        if (modified == null) {
            return Optional.empty();
        }
        return modified;
    }

    @JsonProperty("blendMode")
    public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampBlendMode getBlendMode() {
        return blendMode;
    }

    @JsonIgnore
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> getInReplyTo() {
        if (inReplyTo == null) {
            return Optional.empty();
        }
        return inReplyTo;
    }

    @JsonIgnore
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> getReplyType() {
        if (replyType == null) {
            return Optional.empty();
        }
        return replyType;
    }

    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    @JsonProperty("groupId")
    public Optional<String> getGroupId() {
        return groupId;
    }

    @JsonProperty("createdBy")
    public Optional<String> getCreatedBy() {
        return createdBy;
    }

    @JsonProperty("updatedBy")
    public Optional<String> getUpdatedBy() {
        return updatedBy;
    }

    @JsonProperty("actions")
    public Optional<PdfAnnotationActions> getActions() {
        return actions;
    }

    @JsonIgnore
    public Optional<String> getName() {
        if (name == null) {
            return Optional.empty();
        }
        return name;
    }

    @JsonProperty("rotation")
    public Optional<Double> getRotation() {
        return rotation;
    }

    @JsonProperty("unrotatedRect")
    public Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect> getUnrotatedRect() {
        return unrotatedRect;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("nm")
    private Optional<String> _getNm() {
        return nm;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("contents")
    private Optional<String> _getContents() {
        return contents;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("subject")
    private Optional<String> _getSubject() {
        return subject;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("author")
    private Optional<String> _getAuthor() {
        return author;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("created")
    private Optional<OffsetDateTime> _getCreated() {
        return created;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("modified")
    private Optional<OffsetDateTime> _getModified() {
        return modified;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("inReplyTo")
    private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> _getInReplyTo() {
        return inReplyTo;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("replyType")
    private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> _getReplyType() {
        return replyType;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("name")
    private Optional<String> _getName() {
        return name;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp
                && equalTo((DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp other) {
        return ref.equals(other.ref)
                && pageObjectNumber == other.pageObjectNumber
                && index == other.index
                && identityQuality.equals(other.identityQuality)
                && nm.equals(other.nm)
                && flags.equals(other.flags)
                && rect.equals(other.rect)
                && contents.equals(other.contents)
                && subject.equals(other.subject)
                && author.equals(other.author)
                && created.equals(other.created)
                && modified.equals(other.modified)
                && blendMode.equals(other.blendMode)
                && inReplyTo.equals(other.inReplyTo)
                && replyType.equals(other.replyType)
                && userId.equals(other.userId)
                && groupId.equals(other.groupId)
                && createdBy.equals(other.createdBy)
                && updatedBy.equals(other.updatedBy)
                && actions.equals(other.actions)
                && name.equals(other.name)
                && rotation.equals(other.rotation)
                && unrotatedRect.equals(other.unrotatedRect);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.ref,
                this.pageObjectNumber,
                this.index,
                this.identityQuality,
                this.nm,
                this.flags,
                this.rect,
                this.contents,
                this.subject,
                this.author,
                this.created,
                this.modified,
                this.blendMode,
                this.inReplyTo,
                this.replyType,
                this.userId,
                this.groupId,
                this.createdBy,
                this.updatedBy,
                this.actions,
                this.name,
                this.rotation,
                this.unrotatedRect);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RefStage builder() {
        return new Builder();
    }

    public interface RefStage {
        PageObjectNumberStage ref(@NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef ref);

        Builder from(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp other);
    }

    public interface PageObjectNumberStage {
        IndexStage pageObjectNumber(int pageObjectNumber);
    }

    public interface IndexStage {
        IdentityQualityStage index(int index);
    }

    public interface IdentityQualityStage {
        FlagsStage identityQuality(
                @NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampIdentityQuality identityQuality);
    }

    public interface FlagsStage {
        RectStage flags(@NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampFlags flags);
    }

    public interface RectStage {
        BlendModeStage rect(@NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRect rect);
    }

    public interface BlendModeStage {
        _FinalStage blendMode(
                @NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampBlendMode blendMode);
    }

    public interface _FinalStage {
        DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage nm(Optional<String> nm);

        _FinalStage nm(String nm);

        _FinalStage nm(Nullable<String> nm);

        _FinalStage contents(Optional<String> contents);

        _FinalStage contents(String contents);

        _FinalStage contents(Nullable<String> contents);

        _FinalStage subject(Optional<String> subject);

        _FinalStage subject(String subject);

        _FinalStage subject(Nullable<String> subject);

        _FinalStage author(Optional<String> author);

        _FinalStage author(String author);

        _FinalStage author(Nullable<String> author);

        _FinalStage created(Optional<OffsetDateTime> created);

        _FinalStage created(OffsetDateTime created);

        _FinalStage created(Nullable<OffsetDateTime> created);

        _FinalStage modified(Optional<OffsetDateTime> modified);

        _FinalStage modified(OffsetDateTime modified);

        _FinalStage modified(Nullable<OffsetDateTime> modified);

        _FinalStage inReplyTo(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo);

        _FinalStage inReplyTo(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo inReplyTo);

        _FinalStage inReplyTo(
                Nullable<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo);

        _FinalStage replyType(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType);

        _FinalStage replyType(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType replyType);

        _FinalStage replyType(
                Nullable<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType);

        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);

        _FinalStage groupId(Optional<String> groupId);

        _FinalStage groupId(String groupId);

        _FinalStage createdBy(Optional<String> createdBy);

        _FinalStage createdBy(String createdBy);

        _FinalStage updatedBy(Optional<String> updatedBy);

        _FinalStage updatedBy(String updatedBy);

        _FinalStage actions(Optional<PdfAnnotationActions> actions);

        _FinalStage actions(PdfAnnotationActions actions);

        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        _FinalStage name(Nullable<String> name);

        _FinalStage rotation(Optional<Double> rotation);

        _FinalStage rotation(Double rotation);

        _FinalStage unrotatedRect(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect> unrotatedRect);

        _FinalStage unrotatedRect(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect unrotatedRect);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements RefStage,
                    PageObjectNumberStage,
                    IndexStage,
                    IdentityQualityStage,
                    FlagsStage,
                    RectStage,
                    BlendModeStage,
                    _FinalStage {
        private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef ref;

        private int pageObjectNumber;

        private int index;

        private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampIdentityQuality identityQuality;

        private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampFlags flags;

        private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRect rect;

        private DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampBlendMode blendMode;

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect> unrotatedRect =
                Optional.empty();

        private Optional<Double> rotation = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<PdfAnnotationActions> actions = Optional.empty();

        private Optional<String> updatedBy = Optional.empty();

        private Optional<String> createdBy = Optional.empty();

        private Optional<String> groupId = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType =
                Optional.empty();

        private Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo =
                Optional.empty();

        private Optional<OffsetDateTime> modified = Optional.empty();

        private Optional<OffsetDateTime> created = Optional.empty();

        private Optional<String> author = Optional.empty();

        private Optional<String> subject = Optional.empty();

        private Optional<String> contents = Optional.empty();

        private Optional<String> nm = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp other) {
            ref(other.getRef());
            pageObjectNumber(other.getPageObjectNumber());
            index(other.getIndex());
            identityQuality(other.getIdentityQuality());
            nm(other.getNm());
            flags(other.getFlags());
            rect(other.getRect());
            contents(other.getContents());
            subject(other.getSubject());
            author(other.getAuthor());
            created(other.getCreated());
            modified(other.getModified());
            blendMode(other.getBlendMode());
            inReplyTo(other.getInReplyTo());
            replyType(other.getReplyType());
            userId(other.getUserId());
            groupId(other.getGroupId());
            createdBy(other.getCreatedBy());
            updatedBy(other.getUpdatedBy());
            actions(other.getActions());
            name(other.getName());
            rotation(other.getRotation());
            unrotatedRect(other.getUnrotatedRect());
            return this;
        }

        @java.lang.Override
        @JsonSetter("ref")
        public PageObjectNumberStage ref(
                @NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRef ref) {
            this.ref = Objects.requireNonNull(ref, "ref must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("pageObjectNumber")
        public IndexStage pageObjectNumber(int pageObjectNumber) {
            this.pageObjectNumber = pageObjectNumber;
            return this;
        }

        @java.lang.Override
        @JsonSetter("index")
        public IdentityQualityStage index(int index) {
            this.index = index;
            return this;
        }

        @java.lang.Override
        @JsonSetter("identityQuality")
        public FlagsStage identityQuality(
                @NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampIdentityQuality identityQuality) {
            this.identityQuality = Objects.requireNonNull(identityQuality, "identityQuality must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("flags")
        public RectStage flags(@NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampFlags flags) {
            this.flags = Objects.requireNonNull(flags, "flags must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("rect")
        public BlendModeStage rect(@NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampRect rect) {
            this.rect = Objects.requireNonNull(rect, "rect must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("blendMode")
        public _FinalStage blendMode(
                @NotNull DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampBlendMode blendMode) {
            this.blendMode = Objects.requireNonNull(blendMode, "blendMode must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage unrotatedRect(
                DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect unrotatedRect) {
            this.unrotatedRect = Optional.ofNullable(unrotatedRect);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "unrotatedRect", nulls = Nulls.SKIP)
        public _FinalStage unrotatedRect(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampUnrotatedRect> unrotatedRect) {
            this.unrotatedRect = unrotatedRect;
            return this;
        }

        @java.lang.Override
        public _FinalStage rotation(Double rotation) {
            this.rotation = Optional.ofNullable(rotation);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "rotation", nulls = Nulls.SKIP)
        public _FinalStage rotation(Optional<Double> rotation) {
            this.rotation = rotation;
            return this;
        }

        @java.lang.Override
        public _FinalStage name(Nullable<String> name) {
            if (name.isNull()) {
                this.name = null;
            } else if (name.isEmpty()) {
                this.name = Optional.empty();
            } else {
                this.name = Optional.of(name.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public _FinalStage actions(PdfAnnotationActions actions) {
            this.actions = Optional.ofNullable(actions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "actions", nulls = Nulls.SKIP)
        public _FinalStage actions(Optional<PdfAnnotationActions> actions) {
            this.actions = actions;
            return this;
        }

        @java.lang.Override
        public _FinalStage updatedBy(String updatedBy) {
            this.updatedBy = Optional.ofNullable(updatedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "updatedBy", nulls = Nulls.SKIP)
        public _FinalStage updatedBy(Optional<String> updatedBy) {
            this.updatedBy = updatedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage createdBy(String createdBy) {
            this.createdBy = Optional.ofNullable(createdBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "createdBy", nulls = Nulls.SKIP)
        public _FinalStage createdBy(Optional<String> createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage groupId(String groupId) {
            this.groupId = Optional.ofNullable(groupId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "groupId", nulls = Nulls.SKIP)
        public _FinalStage groupId(Optional<String> groupId) {
            this.groupId = groupId;
            return this;
        }

        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        @java.lang.Override
        public _FinalStage replyType(
                Nullable<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType) {
            if (replyType.isNull()) {
                this.replyType = null;
            } else if (replyType.isEmpty()) {
                this.replyType = Optional.empty();
            } else {
                this.replyType = Optional.of(replyType.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage replyType(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType replyType) {
            this.replyType = Optional.ofNullable(replyType);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "replyType", nulls = Nulls.SKIP)
        public _FinalStage replyType(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType> replyType) {
            this.replyType = replyType;
            return this;
        }

        @java.lang.Override
        public _FinalStage inReplyTo(
                Nullable<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo) {
            if (inReplyTo.isNull()) {
                this.inReplyTo = null;
            } else if (inReplyTo.isEmpty()) {
                this.inReplyTo = Optional.empty();
            } else {
                this.inReplyTo = Optional.of(inReplyTo.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage inReplyTo(DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo inReplyTo) {
            this.inReplyTo = Optional.ofNullable(inReplyTo);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "inReplyTo", nulls = Nulls.SKIP)
        public _FinalStage inReplyTo(
                Optional<DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampInReplyTo> inReplyTo) {
            this.inReplyTo = inReplyTo;
            return this;
        }

        @java.lang.Override
        public _FinalStage modified(Nullable<OffsetDateTime> modified) {
            if (modified.isNull()) {
                this.modified = null;
            } else if (modified.isEmpty()) {
                this.modified = Optional.empty();
            } else {
                this.modified = Optional.of(modified.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage modified(OffsetDateTime modified) {
            this.modified = Optional.ofNullable(modified);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "modified", nulls = Nulls.SKIP)
        public _FinalStage modified(Optional<OffsetDateTime> modified) {
            this.modified = modified;
            return this;
        }

        @java.lang.Override
        public _FinalStage created(Nullable<OffsetDateTime> created) {
            if (created.isNull()) {
                this.created = null;
            } else if (created.isEmpty()) {
                this.created = Optional.empty();
            } else {
                this.created = Optional.of(created.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage created(OffsetDateTime created) {
            this.created = Optional.ofNullable(created);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "created", nulls = Nulls.SKIP)
        public _FinalStage created(Optional<OffsetDateTime> created) {
            this.created = created;
            return this;
        }

        @java.lang.Override
        public _FinalStage author(Nullable<String> author) {
            if (author.isNull()) {
                this.author = null;
            } else if (author.isEmpty()) {
                this.author = Optional.empty();
            } else {
                this.author = Optional.of(author.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage author(String author) {
            this.author = Optional.ofNullable(author);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "author", nulls = Nulls.SKIP)
        public _FinalStage author(Optional<String> author) {
            this.author = author;
            return this;
        }

        @java.lang.Override
        public _FinalStage subject(Nullable<String> subject) {
            if (subject.isNull()) {
                this.subject = null;
            } else if (subject.isEmpty()) {
                this.subject = Optional.empty();
            } else {
                this.subject = Optional.of(subject.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage subject(String subject) {
            this.subject = Optional.ofNullable(subject);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "subject", nulls = Nulls.SKIP)
        public _FinalStage subject(Optional<String> subject) {
            this.subject = subject;
            return this;
        }

        @java.lang.Override
        public _FinalStage contents(Nullable<String> contents) {
            if (contents.isNull()) {
                this.contents = null;
            } else if (contents.isEmpty()) {
                this.contents = Optional.empty();
            } else {
                this.contents = Optional.of(contents.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage contents(String contents) {
            this.contents = Optional.ofNullable(contents);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "contents", nulls = Nulls.SKIP)
        public _FinalStage contents(Optional<String> contents) {
            this.contents = contents;
            return this;
        }

        @java.lang.Override
        public _FinalStage nm(Nullable<String> nm) {
            if (nm.isNull()) {
                this.nm = null;
            } else if (nm.isEmpty()) {
                this.nm = Optional.empty();
            } else {
                this.nm = Optional.of(nm.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage nm(String nm) {
            this.nm = Optional.ofNullable(nm);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "nm", nulls = Nulls.SKIP)
        public _FinalStage nm(Optional<String> nm) {
            this.nm = nm;
            return this;
        }

        @java.lang.Override
        public DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp build() {
            return new DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStamp(
                    ref,
                    pageObjectNumber,
                    index,
                    identityQuality,
                    nm,
                    flags,
                    rect,
                    contents,
                    subject,
                    author,
                    created,
                    modified,
                    blendMode,
                    inReplyTo,
                    replyType,
                    userId,
                    groupId,
                    createdBy,
                    updatedBy,
                    actions,
                    name,
                    rotation,
                    unrotatedRect,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
