/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocAnnotationsList200ResponseAnnotationsItemText.Builder.class)
public final class DocAnnotationsList200ResponseAnnotationsItemText {
    private final DocAnnotationsList200ResponseAnnotationsItemTextRef ref;

    private final int pageObjectNumber;

    private final int index;

    private final DocAnnotationsList200ResponseAnnotationsItemTextIdentityQuality identityQuality;

    private final Optional<String> nm;

    private final DocAnnotationsList200ResponseAnnotationsItemTextFlags flags;

    private final DocAnnotationsList200ResponseAnnotationsItemTextRect rect;

    private final Optional<String> contents;

    private final Optional<String> subject;

    private final Optional<String> author;

    private final Optional<OffsetDateTime> created;

    private final Optional<OffsetDateTime> modified;

    private final DocAnnotationsList200ResponseAnnotationsItemTextBlendMode blendMode;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType;

    private final Optional<String> userId;

    private final Optional<String> groupId;

    private final Optional<String> createdBy;

    private final Optional<String> updatedBy;

    private final Optional<DocAnnotationsList200ResponseAnnotationsItemTextActions> actions;

    private final DocAnnotationsList200ResponseAnnotationsItemTextColor color;

    private final double opacity;

    private final DocAnnotationsList200ResponseAnnotationsItemTextIcon icon;

    private final Optional<String> state;

    private final Optional<String> stateModel;

    private final Map<String, Object> additionalProperties;

    private DocAnnotationsList200ResponseAnnotationsItemText(
            DocAnnotationsList200ResponseAnnotationsItemTextRef ref,
            int pageObjectNumber,
            int index,
            DocAnnotationsList200ResponseAnnotationsItemTextIdentityQuality identityQuality,
            Optional<String> nm,
            DocAnnotationsList200ResponseAnnotationsItemTextFlags flags,
            DocAnnotationsList200ResponseAnnotationsItemTextRect rect,
            Optional<String> contents,
            Optional<String> subject,
            Optional<String> author,
            Optional<OffsetDateTime> created,
            Optional<OffsetDateTime> modified,
            DocAnnotationsList200ResponseAnnotationsItemTextBlendMode blendMode,
            Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo,
            Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType,
            Optional<String> userId,
            Optional<String> groupId,
            Optional<String> createdBy,
            Optional<String> updatedBy,
            Optional<DocAnnotationsList200ResponseAnnotationsItemTextActions> actions,
            DocAnnotationsList200ResponseAnnotationsItemTextColor color,
            double opacity,
            DocAnnotationsList200ResponseAnnotationsItemTextIcon icon,
            Optional<String> state,
            Optional<String> stateModel,
            Map<String, Object> additionalProperties) {
        this.ref = ref;
        this.pageObjectNumber = pageObjectNumber;
        this.index = index;
        this.identityQuality = identityQuality;
        this.nm = nm;
        this.flags = flags;
        this.rect = rect;
        this.contents = contents;
        this.subject = subject;
        this.author = author;
        this.created = created;
        this.modified = modified;
        this.blendMode = blendMode;
        this.inReplyTo = inReplyTo;
        this.replyType = replyType;
        this.userId = userId;
        this.groupId = groupId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.actions = actions;
        this.color = color;
        this.opacity = opacity;
        this.icon = icon;
        this.state = state;
        this.stateModel = stateModel;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("ref")
    public DocAnnotationsList200ResponseAnnotationsItemTextRef getRef() {
        return ref;
    }

    @JsonProperty("pageObjectNumber")
    public int getPageObjectNumber() {
        return pageObjectNumber;
    }

    @JsonProperty("index")
    public int getIndex() {
        return index;
    }

    @JsonProperty("identityQuality")
    public DocAnnotationsList200ResponseAnnotationsItemTextIdentityQuality getIdentityQuality() {
        return identityQuality;
    }

    @JsonIgnore
    public Optional<String> getNm() {
        if (nm == null) {
            return Optional.empty();
        }
        return nm;
    }

    @JsonProperty("flags")
    public DocAnnotationsList200ResponseAnnotationsItemTextFlags getFlags() {
        return flags;
    }

    @JsonProperty("rect")
    public DocAnnotationsList200ResponseAnnotationsItemTextRect getRect() {
        return rect;
    }

    @JsonIgnore
    public Optional<String> getContents() {
        if (contents == null) {
            return Optional.empty();
        }
        return contents;
    }

    @JsonIgnore
    public Optional<String> getSubject() {
        if (subject == null) {
            return Optional.empty();
        }
        return subject;
    }

    @JsonIgnore
    public Optional<String> getAuthor() {
        if (author == null) {
            return Optional.empty();
        }
        return author;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getCreated() {
        if (created == null) {
            return Optional.empty();
        }
        return created;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getModified() {
        if (modified == null) {
            return Optional.empty();
        }
        return modified;
    }

    @JsonProperty("blendMode")
    public DocAnnotationsList200ResponseAnnotationsItemTextBlendMode getBlendMode() {
        return blendMode;
    }

    @JsonIgnore
    public Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> getInReplyTo() {
        if (inReplyTo == null) {
            return Optional.empty();
        }
        return inReplyTo;
    }

    @JsonIgnore
    public Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> getReplyType() {
        if (replyType == null) {
            return Optional.empty();
        }
        return replyType;
    }

    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    @JsonProperty("groupId")
    public Optional<String> getGroupId() {
        return groupId;
    }

    @JsonProperty("createdBy")
    public Optional<String> getCreatedBy() {
        return createdBy;
    }

    @JsonProperty("updatedBy")
    public Optional<String> getUpdatedBy() {
        return updatedBy;
    }

    @JsonProperty("actions")
    public Optional<DocAnnotationsList200ResponseAnnotationsItemTextActions> getActions() {
        return actions;
    }

    @JsonProperty("color")
    public DocAnnotationsList200ResponseAnnotationsItemTextColor getColor() {
        return color;
    }

    @JsonProperty("opacity")
    public double getOpacity() {
        return opacity;
    }

    @JsonProperty("icon")
    public DocAnnotationsList200ResponseAnnotationsItemTextIcon getIcon() {
        return icon;
    }

    @JsonIgnore
    public Optional<String> getState() {
        if (state == null) {
            return Optional.empty();
        }
        return state;
    }

    @JsonIgnore
    public Optional<String> getStateModel() {
        if (stateModel == null) {
            return Optional.empty();
        }
        return stateModel;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("nm")
    private Optional<String> _getNm() {
        return nm;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("contents")
    private Optional<String> _getContents() {
        return contents;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("subject")
    private Optional<String> _getSubject() {
        return subject;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("author")
    private Optional<String> _getAuthor() {
        return author;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("created")
    private Optional<OffsetDateTime> _getCreated() {
        return created;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("modified")
    private Optional<OffsetDateTime> _getModified() {
        return modified;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("inReplyTo")
    private Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> _getInReplyTo() {
        return inReplyTo;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("replyType")
    private Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> _getReplyType() {
        return replyType;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("state")
    private Optional<String> _getState() {
        return state;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("stateModel")
    private Optional<String> _getStateModel() {
        return stateModel;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocAnnotationsList200ResponseAnnotationsItemText
                && equalTo((DocAnnotationsList200ResponseAnnotationsItemText) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocAnnotationsList200ResponseAnnotationsItemText other) {
        return ref.equals(other.ref)
                && pageObjectNumber == other.pageObjectNumber
                && index == other.index
                && identityQuality.equals(other.identityQuality)
                && nm.equals(other.nm)
                && flags.equals(other.flags)
                && rect.equals(other.rect)
                && contents.equals(other.contents)
                && subject.equals(other.subject)
                && author.equals(other.author)
                && created.equals(other.created)
                && modified.equals(other.modified)
                && blendMode.equals(other.blendMode)
                && inReplyTo.equals(other.inReplyTo)
                && replyType.equals(other.replyType)
                && userId.equals(other.userId)
                && groupId.equals(other.groupId)
                && createdBy.equals(other.createdBy)
                && updatedBy.equals(other.updatedBy)
                && actions.equals(other.actions)
                && color.equals(other.color)
                && opacity == other.opacity
                && icon.equals(other.icon)
                && state.equals(other.state)
                && stateModel.equals(other.stateModel);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.ref,
                this.pageObjectNumber,
                this.index,
                this.identityQuality,
                this.nm,
                this.flags,
                this.rect,
                this.contents,
                this.subject,
                this.author,
                this.created,
                this.modified,
                this.blendMode,
                this.inReplyTo,
                this.replyType,
                this.userId,
                this.groupId,
                this.createdBy,
                this.updatedBy,
                this.actions,
                this.color,
                this.opacity,
                this.icon,
                this.state,
                this.stateModel);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RefStage builder() {
        return new Builder();
    }

    public interface RefStage {
        PageObjectNumberStage ref(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextRef ref);

        Builder from(DocAnnotationsList200ResponseAnnotationsItemText other);
    }

    public interface PageObjectNumberStage {
        IndexStage pageObjectNumber(int pageObjectNumber);
    }

    public interface IndexStage {
        IdentityQualityStage index(int index);
    }

    public interface IdentityQualityStage {
        FlagsStage identityQuality(
                @NotNull DocAnnotationsList200ResponseAnnotationsItemTextIdentityQuality identityQuality);
    }

    public interface FlagsStage {
        RectStage flags(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextFlags flags);
    }

    public interface RectStage {
        BlendModeStage rect(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextRect rect);
    }

    public interface BlendModeStage {
        ColorStage blendMode(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextBlendMode blendMode);
    }

    public interface ColorStage {
        OpacityStage color(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextColor color);
    }

    public interface OpacityStage {
        IconStage opacity(double opacity);
    }

    public interface IconStage {
        _FinalStage icon(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextIcon icon);
    }

    public interface _FinalStage {
        DocAnnotationsList200ResponseAnnotationsItemText build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage nm(Optional<String> nm);

        _FinalStage nm(String nm);

        _FinalStage nm(Nullable<String> nm);

        _FinalStage contents(Optional<String> contents);

        _FinalStage contents(String contents);

        _FinalStage contents(Nullable<String> contents);

        _FinalStage subject(Optional<String> subject);

        _FinalStage subject(String subject);

        _FinalStage subject(Nullable<String> subject);

        _FinalStage author(Optional<String> author);

        _FinalStage author(String author);

        _FinalStage author(Nullable<String> author);

        _FinalStage created(Optional<OffsetDateTime> created);

        _FinalStage created(OffsetDateTime created);

        _FinalStage created(Nullable<OffsetDateTime> created);

        _FinalStage modified(Optional<OffsetDateTime> modified);

        _FinalStage modified(OffsetDateTime modified);

        _FinalStage modified(Nullable<OffsetDateTime> modified);

        _FinalStage inReplyTo(Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo);

        _FinalStage inReplyTo(DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo inReplyTo);

        _FinalStage inReplyTo(Nullable<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo);

        _FinalStage replyType(Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType);

        _FinalStage replyType(DocAnnotationsList200ResponseAnnotationsItemTextReplyType replyType);

        _FinalStage replyType(Nullable<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType);

        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);

        _FinalStage groupId(Optional<String> groupId);

        _FinalStage groupId(String groupId);

        _FinalStage createdBy(Optional<String> createdBy);

        _FinalStage createdBy(String createdBy);

        _FinalStage updatedBy(Optional<String> updatedBy);

        _FinalStage updatedBy(String updatedBy);

        _FinalStage actions(Optional<DocAnnotationsList200ResponseAnnotationsItemTextActions> actions);

        _FinalStage actions(DocAnnotationsList200ResponseAnnotationsItemTextActions actions);

        _FinalStage state(Optional<String> state);

        _FinalStage state(String state);

        _FinalStage state(Nullable<String> state);

        _FinalStage stateModel(Optional<String> stateModel);

        _FinalStage stateModel(String stateModel);

        _FinalStage stateModel(Nullable<String> stateModel);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements RefStage,
                    PageObjectNumberStage,
                    IndexStage,
                    IdentityQualityStage,
                    FlagsStage,
                    RectStage,
                    BlendModeStage,
                    ColorStage,
                    OpacityStage,
                    IconStage,
                    _FinalStage {
        private DocAnnotationsList200ResponseAnnotationsItemTextRef ref;

        private int pageObjectNumber;

        private int index;

        private DocAnnotationsList200ResponseAnnotationsItemTextIdentityQuality identityQuality;

        private DocAnnotationsList200ResponseAnnotationsItemTextFlags flags;

        private DocAnnotationsList200ResponseAnnotationsItemTextRect rect;

        private DocAnnotationsList200ResponseAnnotationsItemTextBlendMode blendMode;

        private DocAnnotationsList200ResponseAnnotationsItemTextColor color;

        private double opacity;

        private DocAnnotationsList200ResponseAnnotationsItemTextIcon icon;

        private Optional<String> stateModel = Optional.empty();

        private Optional<String> state = Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemTextActions> actions = Optional.empty();

        private Optional<String> updatedBy = Optional.empty();

        private Optional<String> createdBy = Optional.empty();

        private Optional<String> groupId = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType = Optional.empty();

        private Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo = Optional.empty();

        private Optional<OffsetDateTime> modified = Optional.empty();

        private Optional<OffsetDateTime> created = Optional.empty();

        private Optional<String> author = Optional.empty();

        private Optional<String> subject = Optional.empty();

        private Optional<String> contents = Optional.empty();

        private Optional<String> nm = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocAnnotationsList200ResponseAnnotationsItemText other) {
            ref(other.getRef());
            pageObjectNumber(other.getPageObjectNumber());
            index(other.getIndex());
            identityQuality(other.getIdentityQuality());
            nm(other.getNm());
            flags(other.getFlags());
            rect(other.getRect());
            contents(other.getContents());
            subject(other.getSubject());
            author(other.getAuthor());
            created(other.getCreated());
            modified(other.getModified());
            blendMode(other.getBlendMode());
            inReplyTo(other.getInReplyTo());
            replyType(other.getReplyType());
            userId(other.getUserId());
            groupId(other.getGroupId());
            createdBy(other.getCreatedBy());
            updatedBy(other.getUpdatedBy());
            actions(other.getActions());
            color(other.getColor());
            opacity(other.getOpacity());
            icon(other.getIcon());
            state(other.getState());
            stateModel(other.getStateModel());
            return this;
        }

        @java.lang.Override
        @JsonSetter("ref")
        public PageObjectNumberStage ref(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextRef ref) {
            this.ref = Objects.requireNonNull(ref, "ref must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("pageObjectNumber")
        public IndexStage pageObjectNumber(int pageObjectNumber) {
            this.pageObjectNumber = pageObjectNumber;
            return this;
        }

        @java.lang.Override
        @JsonSetter("index")
        public IdentityQualityStage index(int index) {
            this.index = index;
            return this;
        }

        @java.lang.Override
        @JsonSetter("identityQuality")
        public FlagsStage identityQuality(
                @NotNull DocAnnotationsList200ResponseAnnotationsItemTextIdentityQuality identityQuality) {
            this.identityQuality = Objects.requireNonNull(identityQuality, "identityQuality must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("flags")
        public RectStage flags(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextFlags flags) {
            this.flags = Objects.requireNonNull(flags, "flags must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("rect")
        public BlendModeStage rect(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextRect rect) {
            this.rect = Objects.requireNonNull(rect, "rect must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("blendMode")
        public ColorStage blendMode(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextBlendMode blendMode) {
            this.blendMode = Objects.requireNonNull(blendMode, "blendMode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("color")
        public OpacityStage color(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextColor color) {
            this.color = Objects.requireNonNull(color, "color must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("opacity")
        public IconStage opacity(double opacity) {
            this.opacity = opacity;
            return this;
        }

        @java.lang.Override
        @JsonSetter("icon")
        public _FinalStage icon(@NotNull DocAnnotationsList200ResponseAnnotationsItemTextIcon icon) {
            this.icon = Objects.requireNonNull(icon, "icon must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage stateModel(Nullable<String> stateModel) {
            if (stateModel.isNull()) {
                this.stateModel = null;
            } else if (stateModel.isEmpty()) {
                this.stateModel = Optional.empty();
            } else {
                this.stateModel = Optional.of(stateModel.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage stateModel(String stateModel) {
            this.stateModel = Optional.ofNullable(stateModel);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "stateModel", nulls = Nulls.SKIP)
        public _FinalStage stateModel(Optional<String> stateModel) {
            this.stateModel = stateModel;
            return this;
        }

        @java.lang.Override
        public _FinalStage state(Nullable<String> state) {
            if (state.isNull()) {
                this.state = null;
            } else if (state.isEmpty()) {
                this.state = Optional.empty();
            } else {
                this.state = Optional.of(state.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage state(String state) {
            this.state = Optional.ofNullable(state);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "state", nulls = Nulls.SKIP)
        public _FinalStage state(Optional<String> state) {
            this.state = state;
            return this;
        }

        @java.lang.Override
        public _FinalStage actions(DocAnnotationsList200ResponseAnnotationsItemTextActions actions) {
            this.actions = Optional.ofNullable(actions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "actions", nulls = Nulls.SKIP)
        public _FinalStage actions(Optional<DocAnnotationsList200ResponseAnnotationsItemTextActions> actions) {
            this.actions = actions;
            return this;
        }

        @java.lang.Override
        public _FinalStage updatedBy(String updatedBy) {
            this.updatedBy = Optional.ofNullable(updatedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "updatedBy", nulls = Nulls.SKIP)
        public _FinalStage updatedBy(Optional<String> updatedBy) {
            this.updatedBy = updatedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage createdBy(String createdBy) {
            this.createdBy = Optional.ofNullable(createdBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "createdBy", nulls = Nulls.SKIP)
        public _FinalStage createdBy(Optional<String> createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage groupId(String groupId) {
            this.groupId = Optional.ofNullable(groupId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "groupId", nulls = Nulls.SKIP)
        public _FinalStage groupId(Optional<String> groupId) {
            this.groupId = groupId;
            return this;
        }

        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        @java.lang.Override
        public _FinalStage replyType(Nullable<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType) {
            if (replyType.isNull()) {
                this.replyType = null;
            } else if (replyType.isEmpty()) {
                this.replyType = Optional.empty();
            } else {
                this.replyType = Optional.of(replyType.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage replyType(DocAnnotationsList200ResponseAnnotationsItemTextReplyType replyType) {
            this.replyType = Optional.ofNullable(replyType);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "replyType", nulls = Nulls.SKIP)
        public _FinalStage replyType(Optional<DocAnnotationsList200ResponseAnnotationsItemTextReplyType> replyType) {
            this.replyType = replyType;
            return this;
        }

        @java.lang.Override
        public _FinalStage inReplyTo(Nullable<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo) {
            if (inReplyTo.isNull()) {
                this.inReplyTo = null;
            } else if (inReplyTo.isEmpty()) {
                this.inReplyTo = Optional.empty();
            } else {
                this.inReplyTo = Optional.of(inReplyTo.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage inReplyTo(DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo inReplyTo) {
            this.inReplyTo = Optional.ofNullable(inReplyTo);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "inReplyTo", nulls = Nulls.SKIP)
        public _FinalStage inReplyTo(Optional<DocAnnotationsList200ResponseAnnotationsItemTextInReplyTo> inReplyTo) {
            this.inReplyTo = inReplyTo;
            return this;
        }

        @java.lang.Override
        public _FinalStage modified(Nullable<OffsetDateTime> modified) {
            if (modified.isNull()) {
                this.modified = null;
            } else if (modified.isEmpty()) {
                this.modified = Optional.empty();
            } else {
                this.modified = Optional.of(modified.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage modified(OffsetDateTime modified) {
            this.modified = Optional.ofNullable(modified);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "modified", nulls = Nulls.SKIP)
        public _FinalStage modified(Optional<OffsetDateTime> modified) {
            this.modified = modified;
            return this;
        }

        @java.lang.Override
        public _FinalStage created(Nullable<OffsetDateTime> created) {
            if (created.isNull()) {
                this.created = null;
            } else if (created.isEmpty()) {
                this.created = Optional.empty();
            } else {
                this.created = Optional.of(created.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage created(OffsetDateTime created) {
            this.created = Optional.ofNullable(created);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "created", nulls = Nulls.SKIP)
        public _FinalStage created(Optional<OffsetDateTime> created) {
            this.created = created;
            return this;
        }

        @java.lang.Override
        public _FinalStage author(Nullable<String> author) {
            if (author.isNull()) {
                this.author = null;
            } else if (author.isEmpty()) {
                this.author = Optional.empty();
            } else {
                this.author = Optional.of(author.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage author(String author) {
            this.author = Optional.ofNullable(author);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "author", nulls = Nulls.SKIP)
        public _FinalStage author(Optional<String> author) {
            this.author = author;
            return this;
        }

        @java.lang.Override
        public _FinalStage subject(Nullable<String> subject) {
            if (subject.isNull()) {
                this.subject = null;
            } else if (subject.isEmpty()) {
                this.subject = Optional.empty();
            } else {
                this.subject = Optional.of(subject.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage subject(String subject) {
            this.subject = Optional.ofNullable(subject);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "subject", nulls = Nulls.SKIP)
        public _FinalStage subject(Optional<String> subject) {
            this.subject = subject;
            return this;
        }

        @java.lang.Override
        public _FinalStage contents(Nullable<String> contents) {
            if (contents.isNull()) {
                this.contents = null;
            } else if (contents.isEmpty()) {
                this.contents = Optional.empty();
            } else {
                this.contents = Optional.of(contents.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage contents(String contents) {
            this.contents = Optional.ofNullable(contents);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "contents", nulls = Nulls.SKIP)
        public _FinalStage contents(Optional<String> contents) {
            this.contents = contents;
            return this;
        }

        @java.lang.Override
        public _FinalStage nm(Nullable<String> nm) {
            if (nm.isNull()) {
                this.nm = null;
            } else if (nm.isEmpty()) {
                this.nm = Optional.empty();
            } else {
                this.nm = Optional.of(nm.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage nm(String nm) {
            this.nm = Optional.ofNullable(nm);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "nm", nulls = Nulls.SKIP)
        public _FinalStage nm(Optional<String> nm) {
            this.nm = nm;
            return this;
        }

        @java.lang.Override
        public DocAnnotationsList200ResponseAnnotationsItemText build() {
            return new DocAnnotationsList200ResponseAnnotationsItemText(
                    ref,
                    pageObjectNumber,
                    index,
                    identityQuality,
                    nm,
                    flags,
                    rect,
                    contents,
                    subject,
                    author,
                    created,
                    modified,
                    blendMode,
                    inReplyTo,
                    replyType,
                    userId,
                    groupId,
                    createdBy,
                    updatedBy,
                    actions,
                    color,
                    opacity,
                    icon,
                    state,
                    stateModel,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
