/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocFormsGet200ResponseFieldsItemPushbutton.Builder.class)
public final class DocFormsGet200ResponseFieldsItemPushbutton {
    private final DocFormsGet200ResponseFieldsItemPushbuttonRef ref;

    private final int fieldObjectNumber;

    private final String name;

    private final DocFormsGet200ResponseFieldsItemPushbuttonOrigin origin;

    private final DocFormsGet200ResponseFieldsItemPushbuttonFlags flags;

    private final Optional<String> alternateName;

    private final Optional<String> mappingName;

    private final DocFormsGet200ResponseFieldsItemPushbuttonValueEntry valueEntry;

    private final DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry defaultValueEntry;

    private final Optional<PdfFieldActions> actions;

    private final List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets;

    private final Map<String, Object> additionalProperties;

    private DocFormsGet200ResponseFieldsItemPushbutton(
            DocFormsGet200ResponseFieldsItemPushbuttonRef ref,
            int fieldObjectNumber,
            String name,
            DocFormsGet200ResponseFieldsItemPushbuttonOrigin origin,
            DocFormsGet200ResponseFieldsItemPushbuttonFlags flags,
            Optional<String> alternateName,
            Optional<String> mappingName,
            DocFormsGet200ResponseFieldsItemPushbuttonValueEntry valueEntry,
            DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry defaultValueEntry,
            Optional<PdfFieldActions> actions,
            List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets,
            Map<String, Object> additionalProperties) {
        this.ref = ref;
        this.fieldObjectNumber = fieldObjectNumber;
        this.name = name;
        this.origin = origin;
        this.flags = flags;
        this.alternateName = alternateName;
        this.mappingName = mappingName;
        this.valueEntry = valueEntry;
        this.defaultValueEntry = defaultValueEntry;
        this.actions = actions;
        this.widgets = widgets;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("ref")
    public DocFormsGet200ResponseFieldsItemPushbuttonRef getRef() {
        return ref;
    }

    @JsonProperty("fieldObjectNumber")
    public int getFieldObjectNumber() {
        return fieldObjectNumber;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("origin")
    public DocFormsGet200ResponseFieldsItemPushbuttonOrigin getOrigin() {
        return origin;
    }

    @JsonProperty("flags")
    public DocFormsGet200ResponseFieldsItemPushbuttonFlags getFlags() {
        return flags;
    }

    @JsonIgnore
    public Optional<String> getAlternateName() {
        if (alternateName == null) {
            return Optional.empty();
        }
        return alternateName;
    }

    @JsonIgnore
    public Optional<String> getMappingName() {
        if (mappingName == null) {
            return Optional.empty();
        }
        return mappingName;
    }

    @JsonProperty("valueEntry")
    public DocFormsGet200ResponseFieldsItemPushbuttonValueEntry getValueEntry() {
        return valueEntry;
    }

    @JsonProperty("defaultValueEntry")
    public DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry getDefaultValueEntry() {
        return defaultValueEntry;
    }

    @JsonProperty("actions")
    public Optional<PdfFieldActions> getActions() {
        return actions;
    }

    @JsonProperty("widgets")
    public List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> getWidgets() {
        return widgets;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("alternateName")
    private Optional<String> _getAlternateName() {
        return alternateName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("mappingName")
    private Optional<String> _getMappingName() {
        return mappingName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocFormsGet200ResponseFieldsItemPushbutton
                && equalTo((DocFormsGet200ResponseFieldsItemPushbutton) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocFormsGet200ResponseFieldsItemPushbutton other) {
        return ref.equals(other.ref)
                && fieldObjectNumber == other.fieldObjectNumber
                && name.equals(other.name)
                && origin.equals(other.origin)
                && flags.equals(other.flags)
                && alternateName.equals(other.alternateName)
                && mappingName.equals(other.mappingName)
                && valueEntry.equals(other.valueEntry)
                && defaultValueEntry.equals(other.defaultValueEntry)
                && actions.equals(other.actions)
                && widgets.equals(other.widgets);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.ref,
                this.fieldObjectNumber,
                this.name,
                this.origin,
                this.flags,
                this.alternateName,
                this.mappingName,
                this.valueEntry,
                this.defaultValueEntry,
                this.actions,
                this.widgets);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RefStage builder() {
        return new Builder();
    }

    public interface RefStage {
        FieldObjectNumberStage ref(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonRef ref);

        Builder from(DocFormsGet200ResponseFieldsItemPushbutton other);
    }

    public interface FieldObjectNumberStage {
        NameStage fieldObjectNumber(int fieldObjectNumber);
    }

    public interface NameStage {
        OriginStage name(@NotNull String name);
    }

    public interface OriginStage {
        FlagsStage origin(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonOrigin origin);
    }

    public interface FlagsStage {
        ValueEntryStage flags(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonFlags flags);
    }

    public interface ValueEntryStage {
        DefaultValueEntryStage valueEntry(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonValueEntry valueEntry);
    }

    public interface DefaultValueEntryStage {
        _FinalStage defaultValueEntry(
                @NotNull DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry defaultValueEntry);
    }

    public interface _FinalStage {
        DocFormsGet200ResponseFieldsItemPushbutton build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage alternateName(Optional<String> alternateName);

        _FinalStage alternateName(String alternateName);

        _FinalStage alternateName(Nullable<String> alternateName);

        _FinalStage mappingName(Optional<String> mappingName);

        _FinalStage mappingName(String mappingName);

        _FinalStage mappingName(Nullable<String> mappingName);

        _FinalStage actions(Optional<PdfFieldActions> actions);

        _FinalStage actions(PdfFieldActions actions);

        _FinalStage widgets(List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets);

        _FinalStage addWidgets(DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem widgets);

        _FinalStage addAllWidgets(List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements RefStage,
                    FieldObjectNumberStage,
                    NameStage,
                    OriginStage,
                    FlagsStage,
                    ValueEntryStage,
                    DefaultValueEntryStage,
                    _FinalStage {
        private DocFormsGet200ResponseFieldsItemPushbuttonRef ref;

        private int fieldObjectNumber;

        private String name;

        private DocFormsGet200ResponseFieldsItemPushbuttonOrigin origin;

        private DocFormsGet200ResponseFieldsItemPushbuttonFlags flags;

        private DocFormsGet200ResponseFieldsItemPushbuttonValueEntry valueEntry;

        private DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry defaultValueEntry;

        private List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets = new ArrayList<>();

        private Optional<PdfFieldActions> actions = Optional.empty();

        private Optional<String> mappingName = Optional.empty();

        private Optional<String> alternateName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocFormsGet200ResponseFieldsItemPushbutton other) {
            ref(other.getRef());
            fieldObjectNumber(other.getFieldObjectNumber());
            name(other.getName());
            origin(other.getOrigin());
            flags(other.getFlags());
            alternateName(other.getAlternateName());
            mappingName(other.getMappingName());
            valueEntry(other.getValueEntry());
            defaultValueEntry(other.getDefaultValueEntry());
            actions(other.getActions());
            widgets(other.getWidgets());
            return this;
        }

        @java.lang.Override
        @JsonSetter("ref")
        public FieldObjectNumberStage ref(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonRef ref) {
            this.ref = Objects.requireNonNull(ref, "ref must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("fieldObjectNumber")
        public NameStage fieldObjectNumber(int fieldObjectNumber) {
            this.fieldObjectNumber = fieldObjectNumber;
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public OriginStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("origin")
        public FlagsStage origin(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonOrigin origin) {
            this.origin = Objects.requireNonNull(origin, "origin must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("flags")
        public ValueEntryStage flags(@NotNull DocFormsGet200ResponseFieldsItemPushbuttonFlags flags) {
            this.flags = Objects.requireNonNull(flags, "flags must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("valueEntry")
        public DefaultValueEntryStage valueEntry(
                @NotNull DocFormsGet200ResponseFieldsItemPushbuttonValueEntry valueEntry) {
            this.valueEntry = Objects.requireNonNull(valueEntry, "valueEntry must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("defaultValueEntry")
        public _FinalStage defaultValueEntry(
                @NotNull DocFormsGet200ResponseFieldsItemPushbuttonDefaultValueEntry defaultValueEntry) {
            this.defaultValueEntry = Objects.requireNonNull(defaultValueEntry, "defaultValueEntry must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllWidgets(List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets) {
            if (widgets != null) {
                this.widgets.addAll(widgets);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addWidgets(DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem widgets) {
            this.widgets.add(widgets);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "widgets", nulls = Nulls.SKIP)
        public _FinalStage widgets(List<DocFormsGet200ResponseFieldsItemPushbuttonWidgetsItem> widgets) {
            this.widgets.clear();
            if (widgets != null) {
                this.widgets.addAll(widgets);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage actions(PdfFieldActions actions) {
            this.actions = Optional.ofNullable(actions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "actions", nulls = Nulls.SKIP)
        public _FinalStage actions(Optional<PdfFieldActions> actions) {
            this.actions = actions;
            return this;
        }

        @java.lang.Override
        public _FinalStage mappingName(Nullable<String> mappingName) {
            if (mappingName.isNull()) {
                this.mappingName = null;
            } else if (mappingName.isEmpty()) {
                this.mappingName = Optional.empty();
            } else {
                this.mappingName = Optional.of(mappingName.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage mappingName(String mappingName) {
            this.mappingName = Optional.ofNullable(mappingName);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "mappingName", nulls = Nulls.SKIP)
        public _FinalStage mappingName(Optional<String> mappingName) {
            this.mappingName = mappingName;
            return this;
        }

        @java.lang.Override
        public _FinalStage alternateName(Nullable<String> alternateName) {
            if (alternateName.isNull()) {
                this.alternateName = null;
            } else if (alternateName.isEmpty()) {
                this.alternateName = Optional.empty();
            } else {
                this.alternateName = Optional.of(alternateName.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage alternateName(String alternateName) {
            this.alternateName = Optional.ofNullable(alternateName);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "alternateName", nulls = Nulls.SKIP)
        public _FinalStage alternateName(Optional<String> alternateName) {
            this.alternateName = alternateName;
            return this;
        }

        @java.lang.Override
        public DocFormsGet200ResponseFieldsItemPushbutton build() {
            return new DocFormsGet200ResponseFieldsItemPushbutton(
                    ref,
                    fieldObjectNumber,
                    name,
                    origin,
                    flags,
                    alternateName,
                    mappingName,
                    valueEntry,
                    defaultValueEntry,
                    actions,
                    widgets,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
