/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class DocFormsGet200ResponseFieldsItemTextDefaultValueEntry {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private DocFormsGet200ResponseFieldsItemTextDefaultValueEntry(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static DocFormsGet200ResponseFieldsItemTextDefaultValueEntry none(
            DocFormsGet200ResponseFieldsItemTextDefaultValueEntryNone value) {
        return new DocFormsGet200ResponseFieldsItemTextDefaultValueEntry(new NoneValue(value));
    }

    public static DocFormsGet200ResponseFieldsItemTextDefaultValueEntry scalar(
            DocFormsGet200ResponseFieldsItemTextDefaultValueEntryScalar value) {
        return new DocFormsGet200ResponseFieldsItemTextDefaultValueEntry(new ScalarValue(value));
    }

    public static DocFormsGet200ResponseFieldsItemTextDefaultValueEntry array(
            DocFormsGet200ResponseFieldsItemTextDefaultValueEntryArray value) {
        return new DocFormsGet200ResponseFieldsItemTextDefaultValueEntry(new ArrayValue(value));
    }

    public static DocFormsGet200ResponseFieldsItemTextDefaultValueEntry unsupported(
            DocFormsGet200ResponseFieldsItemTextDefaultValueEntryUnsupported value) {
        return new DocFormsGet200ResponseFieldsItemTextDefaultValueEntry(new UnsupportedValue(value));
    }

    public boolean isNone() {
        return value instanceof NoneValue;
    }

    public boolean isScalar() {
        return value instanceof ScalarValue;
    }

    public boolean isArray() {
        return value instanceof ArrayValue;
    }

    public boolean isUnsupported() {
        return value instanceof UnsupportedValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<DocFormsGet200ResponseFieldsItemTextDefaultValueEntryNone> getNone() {
        if (isNone()) {
            return Optional.of(((NoneValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<DocFormsGet200ResponseFieldsItemTextDefaultValueEntryScalar> getScalar() {
        if (isScalar()) {
            return Optional.of(((ScalarValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<DocFormsGet200ResponseFieldsItemTextDefaultValueEntryArray> getArray() {
        if (isArray()) {
            return Optional.of(((ArrayValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<DocFormsGet200ResponseFieldsItemTextDefaultValueEntryUnsupported> getUnsupported() {
        if (isUnsupported()) {
            return Optional.of(((UnsupportedValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocFormsGet200ResponseFieldsItemTextDefaultValueEntry
                && value.equals(((DocFormsGet200ResponseFieldsItemTextDefaultValueEntry) other).value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitNone(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryNone none);

        T visitScalar(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryScalar scalar);

        T visitArray(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryArray array);

        T visitUnsupported(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryUnsupported unsupported);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "kind", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(NoneValue.class),
        @JsonSubTypes.Type(ScalarValue.class),
        @JsonSubTypes.Type(ArrayValue.class),
        @JsonSubTypes.Type(UnsupportedValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("none")
    @JsonIgnoreProperties("kind")
    private static final class NoneValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocFormsGet200ResponseFieldsItemTextDefaultValueEntryNone value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private NoneValue() {}

        private NoneValue(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryNone value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitNone(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof NoneValue && equalTo((NoneValue) other);
        }

        private boolean equalTo(NoneValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocFormsGet200ResponseFieldsItemTextDefaultValueEntry{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("scalar")
    @JsonIgnoreProperties("kind")
    private static final class ScalarValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocFormsGet200ResponseFieldsItemTextDefaultValueEntryScalar value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ScalarValue() {}

        private ScalarValue(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryScalar value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitScalar(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ScalarValue && equalTo((ScalarValue) other);
        }

        private boolean equalTo(ScalarValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocFormsGet200ResponseFieldsItemTextDefaultValueEntry{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("array")
    @JsonIgnoreProperties("kind")
    private static final class ArrayValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocFormsGet200ResponseFieldsItemTextDefaultValueEntryArray value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private ArrayValue() {}

        private ArrayValue(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryArray value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitArray(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof ArrayValue && equalTo((ArrayValue) other);
        }

        private boolean equalTo(ArrayValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocFormsGet200ResponseFieldsItemTextDefaultValueEntry{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("unsupported")
    @JsonIgnoreProperties("kind")
    private static final class UnsupportedValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "kind", allowSetters = true)
        private DocFormsGet200ResponseFieldsItemTextDefaultValueEntryUnsupported value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private UnsupportedValue() {}

        private UnsupportedValue(DocFormsGet200ResponseFieldsItemTextDefaultValueEntryUnsupported value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitUnsupported(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof UnsupportedValue && equalTo((UnsupportedValue) other);
        }

        private boolean equalTo(UnsupportedValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocFormsGet200ResponseFieldsItemTextDefaultValueEntry{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("kind")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "DocFormsGet200ResponseFieldsItemTextDefaultValueEntry{" + "type: " + type + ", value: " + value
                    + "}";
        }
    }
}
