/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocFormsSetValue200ResponseMeta.Builder.class)
public final class DocFormsSetValue200ResponseMeta {
    private final List<DocFormsSetValue200ResponseMetaAffectedPagesItem> affectedPages;

    private final Optional<DocFormsSetValue200ResponseMetaCacheDelta> cacheDelta;

    private final Map<String, Object> additionalProperties;

    private DocFormsSetValue200ResponseMeta(
            List<DocFormsSetValue200ResponseMetaAffectedPagesItem> affectedPages,
            Optional<DocFormsSetValue200ResponseMetaCacheDelta> cacheDelta,
            Map<String, Object> additionalProperties) {
        this.affectedPages = affectedPages;
        this.cacheDelta = cacheDelta;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("affectedPages")
    public List<DocFormsSetValue200ResponseMetaAffectedPagesItem> getAffectedPages() {
        return affectedPages;
    }

    @JsonIgnore
    public Optional<DocFormsSetValue200ResponseMetaCacheDelta> getCacheDelta() {
        if (cacheDelta == null) {
            return Optional.empty();
        }
        return cacheDelta;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("cacheDelta")
    private Optional<DocFormsSetValue200ResponseMetaCacheDelta> _getCacheDelta() {
        return cacheDelta;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocFormsSetValue200ResponseMeta && equalTo((DocFormsSetValue200ResponseMeta) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocFormsSetValue200ResponseMeta other) {
        return affectedPages.equals(other.affectedPages) && cacheDelta.equals(other.cacheDelta);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.affectedPages, this.cacheDelta);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<DocFormsSetValue200ResponseMetaAffectedPagesItem> affectedPages = new ArrayList<>();

        private Optional<DocFormsSetValue200ResponseMetaCacheDelta> cacheDelta = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DocFormsSetValue200ResponseMeta other) {
            affectedPages(other.getAffectedPages());
            cacheDelta(other.getCacheDelta());
            return this;
        }

        @JsonSetter(value = "affectedPages", nulls = Nulls.SKIP)
        public Builder affectedPages(List<DocFormsSetValue200ResponseMetaAffectedPagesItem> affectedPages) {
            this.affectedPages.clear();
            if (affectedPages != null) {
                this.affectedPages.addAll(affectedPages);
            }
            return this;
        }

        public Builder addAffectedPages(DocFormsSetValue200ResponseMetaAffectedPagesItem affectedPages) {
            this.affectedPages.add(affectedPages);
            return this;
        }

        public Builder addAllAffectedPages(List<DocFormsSetValue200ResponseMetaAffectedPagesItem> affectedPages) {
            if (affectedPages != null) {
                this.affectedPages.addAll(affectedPages);
            }
            return this;
        }

        @JsonSetter(value = "cacheDelta", nulls = Nulls.SKIP)
        public Builder cacheDelta(Optional<DocFormsSetValue200ResponseMetaCacheDelta> cacheDelta) {
            this.cacheDelta = cacheDelta;
            return this;
        }

        public Builder cacheDelta(DocFormsSetValue200ResponseMetaCacheDelta cacheDelta) {
            this.cacheDelta = Optional.ofNullable(cacheDelta);
            return this;
        }

        public Builder cacheDelta(Nullable<DocFormsSetValue200ResponseMetaCacheDelta> cacheDelta) {
            if (cacheDelta.isNull()) {
                this.cacheDelta = null;
            } else if (cacheDelta.isEmpty()) {
                this.cacheDelta = Optional.empty();
            } else {
                this.cacheDelta = Optional.of(cacheDelta.get());
            }
            return this;
        }

        public DocFormsSetValue200ResponseMeta build() {
            return new DocFormsSetValue200ResponseMeta(affectedPages, cacheDelta, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
