/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocManifest200ResponseScopesAttachments {
    public static final DocManifest200ResponseScopesAttachments BASE =
            new DocManifest200ResponseScopesAttachments(Value.BASE, "base");

    public static final DocManifest200ResponseScopesAttachments LAYER =
            new DocManifest200ResponseScopesAttachments(Value.LAYER, "layer");

    private final Value value;

    private final String string;

    DocManifest200ResponseScopesAttachments(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocManifest200ResponseScopesAttachments
                        && this.string.equals(((DocManifest200ResponseScopesAttachments) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BASE:
                return visitor.visitBase();
            case LAYER:
                return visitor.visitLayer();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocManifest200ResponseScopesAttachments valueOf(String value) {
        switch (value) {
            case "base":
                return BASE;
            case "layer":
                return LAYER;
            default:
                return new DocManifest200ResponseScopesAttachments(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BASE,

        LAYER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBase();

        T visitLayer();

        T visitUnknown(String unknownType);
    }
}
