/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition {
    public static final DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition PREFIX =
            new DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition(Value.PREFIX, "prefix");

    public static final DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition SUFFIX =
            new DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition(Value.SUFFIX, "suffix");

    private final Value value;

    private final String string;

    DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition
                        && this.string.equals(
                                ((DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PREFIX:
                return visitor.visitPrefix();
            case SUFFIX:
                return visitor.visitSuffix();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition valueOf(String value) {
        switch (value) {
            case "prefix":
                return PREFIX;
            case "suffix":
                return SUFFIX;
            default:
                return new DocPagesViewports200ResponseItemMeasureRlDistanceItemLabelPosition(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SUFFIX,

        PREFIX,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSuffix();

        T visitPrefix();

        T visitUnknown(String unknownType);
    }
}
