/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocSignaturesAnalysis200Response.Builder.class)
public final class DocSignaturesAnalysis200Response {
    private final DocSignaturesAnalysis200ResponseMode mode;

    private final int policyVersion;

    private final DocSignaturesAnalysis200ResponseBasis basis;

    private final DocSignaturesAnalysis200ResponseSince since;

    private final DocSignaturesAnalysis200ResponseUntil until;

    private final List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions;

    private final DocSignaturesAnalysis200ResponseCurrent current;

    private final DocSignaturesAnalysis200ResponseLater later;

    private final DocSignaturesAnalysis200ResponseVerdict verdict;

    private final List<Object> steps;

    private final Map<String, Object> additionalProperties;

    private DocSignaturesAnalysis200Response(
            DocSignaturesAnalysis200ResponseMode mode,
            int policyVersion,
            DocSignaturesAnalysis200ResponseBasis basis,
            DocSignaturesAnalysis200ResponseSince since,
            DocSignaturesAnalysis200ResponseUntil until,
            List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions,
            DocSignaturesAnalysis200ResponseCurrent current,
            DocSignaturesAnalysis200ResponseLater later,
            DocSignaturesAnalysis200ResponseVerdict verdict,
            List<Object> steps,
            Map<String, Object> additionalProperties) {
        this.mode = mode;
        this.policyVersion = policyVersion;
        this.basis = basis;
        this.since = since;
        this.until = until;
        this.restrictions = restrictions;
        this.current = current;
        this.later = later;
        this.verdict = verdict;
        this.steps = steps;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("mode")
    public DocSignaturesAnalysis200ResponseMode getMode() {
        return mode;
    }

    @JsonProperty("policyVersion")
    public int getPolicyVersion() {
        return policyVersion;
    }

    @JsonProperty("basis")
    public DocSignaturesAnalysis200ResponseBasis getBasis() {
        return basis;
    }

    @JsonProperty("since")
    public DocSignaturesAnalysis200ResponseSince getSince() {
        return since;
    }

    @JsonProperty("until")
    public DocSignaturesAnalysis200ResponseUntil getUntil() {
        return until;
    }

    @JsonProperty("restrictions")
    public List<DocSignaturesAnalysis200ResponseRestrictionsItem> getRestrictions() {
        return restrictions;
    }

    @JsonProperty("current")
    public DocSignaturesAnalysis200ResponseCurrent getCurrent() {
        return current;
    }

    @JsonProperty("later")
    public DocSignaturesAnalysis200ResponseLater getLater() {
        return later;
    }

    @JsonProperty("verdict")
    public DocSignaturesAnalysis200ResponseVerdict getVerdict() {
        return verdict;
    }

    @JsonProperty("steps")
    public List<Object> getSteps() {
        return steps;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocSignaturesAnalysis200Response && equalTo((DocSignaturesAnalysis200Response) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocSignaturesAnalysis200Response other) {
        return mode.equals(other.mode)
                && policyVersion == other.policyVersion
                && basis.equals(other.basis)
                && since.equals(other.since)
                && until.equals(other.until)
                && restrictions.equals(other.restrictions)
                && current.equals(other.current)
                && later.equals(other.later)
                && verdict.equals(other.verdict)
                && steps.equals(other.steps);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.mode,
                this.policyVersion,
                this.basis,
                this.since,
                this.until,
                this.restrictions,
                this.current,
                this.later,
                this.verdict,
                this.steps);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ModeStage builder() {
        return new Builder();
    }

    public interface ModeStage {
        PolicyVersionStage mode(@NotNull DocSignaturesAnalysis200ResponseMode mode);

        Builder from(DocSignaturesAnalysis200Response other);
    }

    public interface PolicyVersionStage {
        BasisStage policyVersion(int policyVersion);
    }

    public interface BasisStage {
        SinceStage basis(@NotNull DocSignaturesAnalysis200ResponseBasis basis);
    }

    public interface SinceStage {
        UntilStage since(@NotNull DocSignaturesAnalysis200ResponseSince since);
    }

    public interface UntilStage {
        CurrentStage until(@NotNull DocSignaturesAnalysis200ResponseUntil until);
    }

    public interface CurrentStage {
        LaterStage current(@NotNull DocSignaturesAnalysis200ResponseCurrent current);
    }

    public interface LaterStage {
        VerdictStage later(@NotNull DocSignaturesAnalysis200ResponseLater later);
    }

    public interface VerdictStage {
        _FinalStage verdict(@NotNull DocSignaturesAnalysis200ResponseVerdict verdict);
    }

    public interface _FinalStage {
        DocSignaturesAnalysis200Response build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage restrictions(List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions);

        _FinalStage addRestrictions(DocSignaturesAnalysis200ResponseRestrictionsItem restrictions);

        _FinalStage addAllRestrictions(List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions);

        _FinalStage steps(List<Object> steps);

        _FinalStage addSteps(Object steps);

        _FinalStage addAllSteps(List<Object> steps);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ModeStage,
                    PolicyVersionStage,
                    BasisStage,
                    SinceStage,
                    UntilStage,
                    CurrentStage,
                    LaterStage,
                    VerdictStage,
                    _FinalStage {
        private DocSignaturesAnalysis200ResponseMode mode;

        private int policyVersion;

        private DocSignaturesAnalysis200ResponseBasis basis;

        private DocSignaturesAnalysis200ResponseSince since;

        private DocSignaturesAnalysis200ResponseUntil until;

        private DocSignaturesAnalysis200ResponseCurrent current;

        private DocSignaturesAnalysis200ResponseLater later;

        private DocSignaturesAnalysis200ResponseVerdict verdict;

        private List<Object> steps = new ArrayList<>();

        private List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocSignaturesAnalysis200Response other) {
            mode(other.getMode());
            policyVersion(other.getPolicyVersion());
            basis(other.getBasis());
            since(other.getSince());
            until(other.getUntil());
            restrictions(other.getRestrictions());
            current(other.getCurrent());
            later(other.getLater());
            verdict(other.getVerdict());
            steps(other.getSteps());
            return this;
        }

        @java.lang.Override
        @JsonSetter("mode")
        public PolicyVersionStage mode(@NotNull DocSignaturesAnalysis200ResponseMode mode) {
            this.mode = Objects.requireNonNull(mode, "mode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("policyVersion")
        public BasisStage policyVersion(int policyVersion) {
            this.policyVersion = policyVersion;
            return this;
        }

        @java.lang.Override
        @JsonSetter("basis")
        public SinceStage basis(@NotNull DocSignaturesAnalysis200ResponseBasis basis) {
            this.basis = Objects.requireNonNull(basis, "basis must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("since")
        public UntilStage since(@NotNull DocSignaturesAnalysis200ResponseSince since) {
            this.since = Objects.requireNonNull(since, "since must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("until")
        public CurrentStage until(@NotNull DocSignaturesAnalysis200ResponseUntil until) {
            this.until = Objects.requireNonNull(until, "until must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("current")
        public LaterStage current(@NotNull DocSignaturesAnalysis200ResponseCurrent current) {
            this.current = Objects.requireNonNull(current, "current must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("later")
        public VerdictStage later(@NotNull DocSignaturesAnalysis200ResponseLater later) {
            this.later = Objects.requireNonNull(later, "later must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("verdict")
        public _FinalStage verdict(@NotNull DocSignaturesAnalysis200ResponseVerdict verdict) {
            this.verdict = Objects.requireNonNull(verdict, "verdict must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllSteps(List<Object> steps) {
            if (steps != null) {
                this.steps.addAll(steps);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addSteps(Object steps) {
            this.steps.add(steps);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "steps", nulls = Nulls.SKIP)
        public _FinalStage steps(List<Object> steps) {
            this.steps.clear();
            if (steps != null) {
                this.steps.addAll(steps);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllRestrictions(List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions) {
            if (restrictions != null) {
                this.restrictions.addAll(restrictions);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addRestrictions(DocSignaturesAnalysis200ResponseRestrictionsItem restrictions) {
            this.restrictions.add(restrictions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "restrictions", nulls = Nulls.SKIP)
        public _FinalStage restrictions(List<DocSignaturesAnalysis200ResponseRestrictionsItem> restrictions) {
            this.restrictions.clear();
            if (restrictions != null) {
                this.restrictions.addAll(restrictions);
            }
            return this;
        }

        @java.lang.Override
        public DocSignaturesAnalysis200Response build() {
            return new DocSignaturesAnalysis200Response(
                    mode,
                    policyVersion,
                    basis,
                    since,
                    until,
                    restrictions,
                    current,
                    later,
                    verdict,
                    steps,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
