/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocSignaturesList200ResponseSignaturesItemKind {
    public static final DocSignaturesList200ResponseSignaturesItemKind SIGNATURE =
            new DocSignaturesList200ResponseSignaturesItemKind(Value.SIGNATURE, "signature");

    public static final DocSignaturesList200ResponseSignaturesItemKind TIMESTAMP =
            new DocSignaturesList200ResponseSignaturesItemKind(Value.TIMESTAMP, "timestamp");

    private final Value value;

    private final String string;

    DocSignaturesList200ResponseSignaturesItemKind(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocSignaturesList200ResponseSignaturesItemKind
                        && this.string.equals(((DocSignaturesList200ResponseSignaturesItemKind) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SIGNATURE:
                return visitor.visitSignature();
            case TIMESTAMP:
                return visitor.visitTimestamp();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocSignaturesList200ResponseSignaturesItemKind valueOf(String value) {
        switch (value) {
            case "signature":
                return SIGNATURE;
            case "timestamp":
                return TIMESTAMP;
            default:
                return new DocSignaturesList200ResponseSignaturesItemKind(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SIGNATURE,

        TIMESTAMP,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSignature();

        T visitTimestamp();

        T visitUnknown(String unknownType);
    }
}
