/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DocumentsImportFrom202ResponseTag {
    public static final DocumentsImportFrom202ResponseTag IMPORTED =
            new DocumentsImportFrom202ResponseTag(Value.IMPORTED, "imported");

    public static final DocumentsImportFrom202ResponseTag DEDUPED =
            new DocumentsImportFrom202ResponseTag(Value.DEDUPED, "deduped");

    public static final DocumentsImportFrom202ResponseTag ACCEPTED =
            new DocumentsImportFrom202ResponseTag(Value.ACCEPTED, "accepted");

    private final Value value;

    private final String string;

    DocumentsImportFrom202ResponseTag(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DocumentsImportFrom202ResponseTag
                        && this.string.equals(((DocumentsImportFrom202ResponseTag) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case IMPORTED:
                return visitor.visitImported();
            case DEDUPED:
                return visitor.visitDeduped();
            case ACCEPTED:
                return visitor.visitAccepted();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DocumentsImportFrom202ResponseTag valueOf(String value) {
        switch (value) {
            case "imported":
                return IMPORTED;
            case "deduped":
                return DEDUPED;
            case "accepted":
                return ACCEPTED;
            default:
                return new DocumentsImportFrom202ResponseTag(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        IMPORTED,

        DEDUPED,

        ACCEPTED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitImported();

        T visitDeduped();

        T visitAccepted();

        T visitUnknown(String unknownType);
    }
}
