/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocVersionsSignatures200Response.Builder.class)
public final class DocVersionsSignatures200Response {
    private final boolean chainValid;

    private final List<DocVersionsSignatures200ResponseRevisionsItem> revisions;

    private final List<DocVersionsSignatures200ResponseSignaturesItem> signatures;

    private final DocVersionsSignatures200ResponseProtection protection;

    private final Map<String, Object> additionalProperties;

    private DocVersionsSignatures200Response(
            boolean chainValid,
            List<DocVersionsSignatures200ResponseRevisionsItem> revisions,
            List<DocVersionsSignatures200ResponseSignaturesItem> signatures,
            DocVersionsSignatures200ResponseProtection protection,
            Map<String, Object> additionalProperties) {
        this.chainValid = chainValid;
        this.revisions = revisions;
        this.signatures = signatures;
        this.protection = protection;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("chainValid")
    public boolean getChainValid() {
        return chainValid;
    }

    @JsonProperty("revisions")
    public List<DocVersionsSignatures200ResponseRevisionsItem> getRevisions() {
        return revisions;
    }

    @JsonProperty("signatures")
    public List<DocVersionsSignatures200ResponseSignaturesItem> getSignatures() {
        return signatures;
    }

    @JsonProperty("protection")
    public DocVersionsSignatures200ResponseProtection getProtection() {
        return protection;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocVersionsSignatures200Response && equalTo((DocVersionsSignatures200Response) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocVersionsSignatures200Response other) {
        return chainValid == other.chainValid
                && revisions.equals(other.revisions)
                && signatures.equals(other.signatures)
                && protection.equals(other.protection);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.chainValid, this.revisions, this.signatures, this.protection);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ChainValidStage builder() {
        return new Builder();
    }

    public interface ChainValidStage {
        ProtectionStage chainValid(boolean chainValid);

        Builder from(DocVersionsSignatures200Response other);
    }

    public interface ProtectionStage {
        _FinalStage protection(@NotNull DocVersionsSignatures200ResponseProtection protection);
    }

    public interface _FinalStage {
        DocVersionsSignatures200Response build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage revisions(List<DocVersionsSignatures200ResponseRevisionsItem> revisions);

        _FinalStage addRevisions(DocVersionsSignatures200ResponseRevisionsItem revisions);

        _FinalStage addAllRevisions(List<DocVersionsSignatures200ResponseRevisionsItem> revisions);

        _FinalStage signatures(List<DocVersionsSignatures200ResponseSignaturesItem> signatures);

        _FinalStage addSignatures(DocVersionsSignatures200ResponseSignaturesItem signatures);

        _FinalStage addAllSignatures(List<DocVersionsSignatures200ResponseSignaturesItem> signatures);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ChainValidStage, ProtectionStage, _FinalStage {
        private boolean chainValid;

        private DocVersionsSignatures200ResponseProtection protection;

        private List<DocVersionsSignatures200ResponseSignaturesItem> signatures = new ArrayList<>();

        private List<DocVersionsSignatures200ResponseRevisionsItem> revisions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DocVersionsSignatures200Response other) {
            chainValid(other.getChainValid());
            revisions(other.getRevisions());
            signatures(other.getSignatures());
            protection(other.getProtection());
            return this;
        }

        @java.lang.Override
        @JsonSetter("chainValid")
        public ProtectionStage chainValid(boolean chainValid) {
            this.chainValid = chainValid;
            return this;
        }

        @java.lang.Override
        @JsonSetter("protection")
        public _FinalStage protection(@NotNull DocVersionsSignatures200ResponseProtection protection) {
            this.protection = Objects.requireNonNull(protection, "protection must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllSignatures(List<DocVersionsSignatures200ResponseSignaturesItem> signatures) {
            if (signatures != null) {
                this.signatures.addAll(signatures);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addSignatures(DocVersionsSignatures200ResponseSignaturesItem signatures) {
            this.signatures.add(signatures);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "signatures", nulls = Nulls.SKIP)
        public _FinalStage signatures(List<DocVersionsSignatures200ResponseSignaturesItem> signatures) {
            this.signatures.clear();
            if (signatures != null) {
                this.signatures.addAll(signatures);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllRevisions(List<DocVersionsSignatures200ResponseRevisionsItem> revisions) {
            if (revisions != null) {
                this.revisions.addAll(revisions);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addRevisions(DocVersionsSignatures200ResponseRevisionsItem revisions) {
            this.revisions.add(revisions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "revisions", nulls = Nulls.SKIP)
        public _FinalStage revisions(List<DocVersionsSignatures200ResponseRevisionsItem> revisions) {
            this.revisions.clear();
            if (revisions != null) {
                this.revisions.addAll(revisions);
            }
            return this;
        }

        @java.lang.Override
        public DocVersionsSignatures200Response build() {
            return new DocVersionsSignatures200Response(
                    chainValid, revisions, signatures, protection, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
