/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SharesList200Response.Builder.class)
public final class SharesList200Response {
    private final List<SharesList200ResponseSharesItem> shares;

    private final Optional<String> nextCursor;

    private final Map<String, Object> additionalProperties;

    private SharesList200Response(
            List<SharesList200ResponseSharesItem> shares,
            Optional<String> nextCursor,
            Map<String, Object> additionalProperties) {
        this.shares = shares;
        this.nextCursor = nextCursor;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("shares")
    public List<SharesList200ResponseSharesItem> getShares() {
        return shares;
    }

    @JsonIgnore
    public Optional<String> getNextCursor() {
        if (nextCursor == null) {
            return Optional.empty();
        }
        return nextCursor;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("nextCursor")
    private Optional<String> _getNextCursor() {
        return nextCursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SharesList200Response && equalTo((SharesList200Response) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SharesList200Response other) {
        return shares.equals(other.shares) && nextCursor.equals(other.nextCursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.shares, this.nextCursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<SharesList200ResponseSharesItem> shares = new ArrayList<>();

        private Optional<String> nextCursor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SharesList200Response other) {
            shares(other.getShares());
            nextCursor(other.getNextCursor());
            return this;
        }

        @JsonSetter(value = "shares", nulls = Nulls.SKIP)
        public Builder shares(List<SharesList200ResponseSharesItem> shares) {
            this.shares.clear();
            if (shares != null) {
                this.shares.addAll(shares);
            }
            return this;
        }

        public Builder addShares(SharesList200ResponseSharesItem shares) {
            this.shares.add(shares);
            return this;
        }

        public Builder addAllShares(List<SharesList200ResponseSharesItem> shares) {
            if (shares != null) {
                this.shares.addAll(shares);
            }
            return this;
        }

        @JsonSetter(value = "nextCursor", nulls = Nulls.SKIP)
        public Builder nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        public Builder nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        public Builder nextCursor(Nullable<String> nextCursor) {
            if (nextCursor.isNull()) {
                this.nextCursor = null;
            } else if (nextCursor.isEmpty()) {
                this.nextCursor = Optional.empty();
            } else {
                this.nextCursor = Optional.of(nextCursor.get());
            }
            return this;
        }

        public SharesList200Response build() {
            return new SharesList200Response(shares, nextCursor, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
