/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cloudpdf.api.types;

import com.cloudpdf.api.core.Nullable;
import com.cloudpdf.api.core.NullableNonemptyFilter;
import com.cloudpdf.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TenantsList200Response.Builder.class)
public final class TenantsList200Response {
    private final List<TenantsList200ResponseTenantsItem> tenants;

    private final Optional<String> nextCursor;

    private final Map<String, Object> additionalProperties;

    private TenantsList200Response(
            List<TenantsList200ResponseTenantsItem> tenants,
            Optional<String> nextCursor,
            Map<String, Object> additionalProperties) {
        this.tenants = tenants;
        this.nextCursor = nextCursor;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("tenants")
    public List<TenantsList200ResponseTenantsItem> getTenants() {
        return tenants;
    }

    @JsonIgnore
    public Optional<String> getNextCursor() {
        if (nextCursor == null) {
            return Optional.empty();
        }
        return nextCursor;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("nextCursor")
    private Optional<String> _getNextCursor() {
        return nextCursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TenantsList200Response && equalTo((TenantsList200Response) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TenantsList200Response other) {
        return tenants.equals(other.tenants) && nextCursor.equals(other.nextCursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.tenants, this.nextCursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<TenantsList200ResponseTenantsItem> tenants = new ArrayList<>();

        private Optional<String> nextCursor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TenantsList200Response other) {
            tenants(other.getTenants());
            nextCursor(other.getNextCursor());
            return this;
        }

        @JsonSetter(value = "tenants", nulls = Nulls.SKIP)
        public Builder tenants(List<TenantsList200ResponseTenantsItem> tenants) {
            this.tenants.clear();
            if (tenants != null) {
                this.tenants.addAll(tenants);
            }
            return this;
        }

        public Builder addTenants(TenantsList200ResponseTenantsItem tenants) {
            this.tenants.add(tenants);
            return this;
        }

        public Builder addAllTenants(List<TenantsList200ResponseTenantsItem> tenants) {
            if (tenants != null) {
                this.tenants.addAll(tenants);
            }
            return this;
        }

        @JsonSetter(value = "nextCursor", nulls = Nulls.SKIP)
        public Builder nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        public Builder nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        public Builder nextCursor(Nullable<String> nextCursor) {
            if (nextCursor.isNull()) {
                this.nextCursor = null;
            } else if (nextCursor.isEmpty()) {
                this.nextCursor = Optional.empty();
            } else {
                this.nextCursor = Optional.of(nextCursor.get());
            }
            return this;
        }

        public TenantsList200Response build() {
            return new TenantsList200Response(tenants, nextCursor, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
